import type { ClassDefinition } from "./types";

// Every class below now carries its FULL SRD "Ability Score Improvement"
// progression (4th/8th/12th/16th/19th for every class, plus Fighter's extra
// 6th/14th and Rogue's extra 10th) — added for the level-up wizard's ASI
// step, which finds its gate levels by name in a class's own `features`
// array rather than a hardcoded level list (some classes/subclasses have
// non-vanilla ASI levels, so the level must come from data, not a constant).
// Originally only Barbarian (level 4 only) and Fighter (already complete)
// had any "Ability Score Improvement" entries at all; every other class's
// entries here are a new, deliberate completion of this file's existing
// data, not a change to any entry that was already present.
export const CLASSES: ClassDefinition[] = [
  {
    name: "Barbarian",
    hitDie: 12,
    savingThrowProficiencies: ["strength", "constitution"],
    casterProgression: "none",
    features: [
      { name: "Rage", level: 1 },
      { name: "Unarmored Defense", level: 1 },
      { name: "Reckless Attack", level: 2 },
      { name: "Danger Sense", level: 2 },
      { name: "Primal Path", level: 3 },
      { name: "Ability Score Improvement", level: 4 },
      { name: "Extra Attack", level: 5 },
      { name: "Fast Movement", level: 5 },
      { name: "Feral Instinct", level: 7 },
      { name: "Ability Score Improvement", level: 8 },
      { name: "Brutal Critical", level: 9 },
      { name: "Relentless Rage", level: 11 },
      { name: "Ability Score Improvement", level: 12 },
      { name: "Persistent Rage", level: 15 },
      { name: "Ability Score Improvement", level: 16 },
      { name: "Indomitable Might", level: 18 },
      { name: "Ability Score Improvement", level: 19 },
      { name: "Primal Champion", level: 20 },
    ],
  },
  {
    name: "Bard",
    hitDie: 8,
    savingThrowProficiencies: ["dexterity", "charisma"],
    spellcastingAbility: "charisma",
    casterProgression: "full",
    features: [
      { name: "Spellcasting", level: 1 },
      { name: "Bardic Inspiration", level: 1 },
      { name: "Jack of All Trades", level: 2 },
      { name: "Song of Rest", level: 2 },
      { name: "Bard College", level: 3 },
      { name: "Expertise", level: 3 },
      { name: "Ability Score Improvement", level: 4 },
      { name: "Font of Inspiration", level: 5 },
      { name: "Countercharm", level: 6 },
      { name: "Ability Score Improvement", level: 8 },
      { name: "Magical Secrets", level: 10 },
      { name: "Ability Score Improvement", level: 12 },
      { name: "Ability Score Improvement", level: 16 },
      { name: "Ability Score Improvement", level: 19 },
      { name: "Superior Inspiration", level: 20 },
    ],
  },
  {
    name: "Cleric",
    hitDie: 8,
    savingThrowProficiencies: ["wisdom", "charisma"],
    spellcastingAbility: "wisdom",
    casterProgression: "full",
    features: [
      { name: "Spellcasting", level: 1 },
      { name: "Divine Domain", level: 1 },
      { name: "Channel Divinity", level: 2 },
      { name: "Ability Score Improvement", level: 4 },
      { name: "Destroy Undead", level: 5 },
      { name: "Ability Score Improvement", level: 8 },
      { name: "Divine Intervention", level: 10 },
      { name: "Ability Score Improvement", level: 12 },
      { name: "Ability Score Improvement", level: 16 },
      { name: "Ability Score Improvement", level: 19 },
    ],
  },
  {
    name: "Druid",
    hitDie: 8,
    savingThrowProficiencies: ["intelligence", "wisdom"],
    spellcastingAbility: "wisdom",
    casterProgression: "full",
    features: [
      { name: "Druidic", level: 1 },
      { name: "Spellcasting", level: 1 },
      { name: "Wild Shape", level: 2 },
      { name: "Druid Circle", level: 2 },
      { name: "Ability Score Improvement", level: 4 },
      { name: "Ability Score Improvement", level: 8 },
      { name: "Ability Score Improvement", level: 12 },
      { name: "Ability Score Improvement", level: 16 },
      { name: "Timeless Body", level: 18 },
      { name: "Beast Spells", level: 18 },
      { name: "Ability Score Improvement", level: 19 },
      { name: "Archdruid", level: 20 },
    ],
  },
  {
    name: "Fighter",
    hitDie: 10,
    savingThrowProficiencies: ["strength", "constitution"],
    casterProgression: "none",
    features: [
      { name: "Fighting Style", level: 1 },
      { name: "Second Wind", level: 1 },
      { name: "Action Surge", level: 2 },
      { name: "Martial Archetype", level: 3 },
      { name: "Ability Score Improvement", level: 4 },
      { name: "Extra Attack", level: 5 },
      { name: "Ability Score Improvement", level: 6 },
      { name: "Ability Score Improvement", level: 8 },
      { name: "Indomitable", level: 9 },
      { name: "Extra Attack (2)", level: 11 },
      { name: "Ability Score Improvement", level: 12 },
      { name: "Ability Score Improvement", level: 14 },
      { name: "Ability Score Improvement", level: 16 },
      { name: "Action Surge (2 uses)", level: 17 },
      { name: "Ability Score Improvement", level: 19 },
      { name: "Extra Attack (3)", level: 20 },
    ],
  },
  {
    name: "Monk",
    hitDie: 8,
    savingThrowProficiencies: ["strength", "dexterity"],
    casterProgression: "none",
    features: [
      { name: "Unarmored Defense", level: 1 },
      { name: "Martial Arts", level: 1 },
      { name: "Ki", level: 2 },
      { name: "Unarmored Movement", level: 2 },
      { name: "Monastic Tradition", level: 3 },
      { name: "Deflect Missiles", level: 3 },
      { name: "Ability Score Improvement", level: 4 },
      { name: "Slow Fall", level: 4 },
      { name: "Extra Attack", level: 5 },
      { name: "Stunning Strike", level: 5 },
      { name: "Ki-Empowered Strikes", level: 6 },
      { name: "Evasion", level: 7 },
      { name: "Stillness of Mind", level: 7 },
      { name: "Ability Score Improvement", level: 8 },
      { name: "Purity of Body", level: 10 },
      { name: "Ability Score Improvement", level: 12 },
      { name: "Tongue of the Sun and Moon", level: 13 },
      { name: "Diamond Soul", level: 14 },
      { name: "Timeless Body", level: 15 },
      { name: "Ability Score Improvement", level: 16 },
      { name: "Empty Body", level: 18 },
      { name: "Ability Score Improvement", level: 19 },
      { name: "Perfect Self", level: 20 },
    ],
  },
  {
    name: "Paladin",
    hitDie: 10,
    savingThrowProficiencies: ["wisdom", "charisma"],
    spellcastingAbility: "charisma",
    casterProgression: "half",
    features: [
      { name: "Divine Sense", level: 1 },
      { name: "Lay on Hands", level: 1 },
      { name: "Fighting Style", level: 2 },
      { name: "Spellcasting", level: 2 },
      { name: "Divine Smite", level: 2 },
      { name: "Divine Health", level: 3 },
      { name: "Sacred Oath", level: 3 },
      { name: "Ability Score Improvement", level: 4 },
      { name: "Extra Attack", level: 5 },
      { name: "Aura of Protection", level: 6 },
      { name: "Ability Score Improvement", level: 8 },
      { name: "Aura of Courage", level: 10 },
      { name: "Improved Divine Smite", level: 11 },
      { name: "Ability Score Improvement", level: 12 },
      { name: "Cleansing Touch", level: 14 },
      { name: "Ability Score Improvement", level: 16 },
      { name: "Ability Score Improvement", level: 19 },
    ],
  },
  {
    name: "Ranger",
    hitDie: 10,
    savingThrowProficiencies: ["strength", "dexterity"],
    spellcastingAbility: "wisdom",
    casterProgression: "half",
    features: [
      { name: "Favored Enemy", level: 1 },
      { name: "Natural Explorer", level: 1 },
      { name: "Fighting Style", level: 2 },
      { name: "Spellcasting", level: 2 },
      { name: "Ranger Archetype", level: 3 },
      { name: "Primeval Awareness", level: 3 },
      { name: "Ability Score Improvement", level: 4 },
      { name: "Extra Attack", level: 5 },
      { name: "Ability Score Improvement", level: 8 },
      { name: "Land's Stride", level: 8 },
      { name: "Hide in Plain Sight", level: 10 },
      { name: "Ability Score Improvement", level: 12 },
      { name: "Vanish", level: 14 },
      { name: "Ability Score Improvement", level: 16 },
      { name: "Feral Senses", level: 18 },
      { name: "Ability Score Improvement", level: 19 },
      { name: "Foe Slayer", level: 20 },
    ],
  },
  {
    name: "Rogue",
    hitDie: 8,
    savingThrowProficiencies: ["dexterity", "intelligence"],
    casterProgression: "none",
    features: [
      { name: "Expertise", level: 1 },
      { name: "Sneak Attack", level: 1 },
      { name: "Thieves' Cant", level: 1 },
      { name: "Cunning Action", level: 2 },
      { name: "Roguish Archetype", level: 3 },
      { name: "Ability Score Improvement", level: 4 },
      { name: "Uncanny Dodge", level: 5 },
      { name: "Evasion", level: 7 },
      { name: "Ability Score Improvement", level: 8 },
      { name: "Ability Score Improvement", level: 10 },
      { name: "Reliable Talent", level: 11 },
      { name: "Ability Score Improvement", level: 12 },
      { name: "Blindsense", level: 14 },
      { name: "Slippery Mind", level: 15 },
      { name: "Ability Score Improvement", level: 16 },
      { name: "Elusive", level: 18 },
      { name: "Ability Score Improvement", level: 19 },
      { name: "Stroke of Luck", level: 20 },
    ],
  },
  {
    name: "Sorcerer",
    hitDie: 6,
    savingThrowProficiencies: ["constitution", "charisma"],
    spellcastingAbility: "charisma",
    casterProgression: "full",
    features: [
      { name: "Spellcasting", level: 1 },
      { name: "Sorcerous Origin", level: 1 },
      { name: "Font of Magic", level: 2 },
      { name: "Metamagic", level: 3 },
      { name: "Ability Score Improvement", level: 4 },
      { name: "Ability Score Improvement", level: 8 },
      { name: "Ability Score Improvement", level: 12 },
      { name: "Ability Score Improvement", level: 16 },
      { name: "Ability Score Improvement", level: 19 },
      { name: "Sorcerous Restoration", level: 20 },
    ],
  },
  {
    name: "Warlock",
    hitDie: 8,
    savingThrowProficiencies: ["wisdom", "charisma"],
    spellcastingAbility: "charisma",
    casterProgression: "pact",
    features: [
      { name: "Otherworldly Patron", level: 1 },
      { name: "Pact Magic", level: 1 },
      { name: "Eldritch Invocations", level: 2 },
      { name: "Pact Boon", level: 3 },
      { name: "Ability Score Improvement", level: 4 },
      { name: "Ability Score Improvement", level: 8 },
      { name: "Mystic Arcanum (6th level)", level: 11 },
      { name: "Ability Score Improvement", level: 12 },
      { name: "Mystic Arcanum (7th level)", level: 13 },
      { name: "Mystic Arcanum (8th level)", level: 15 },
      { name: "Ability Score Improvement", level: 16 },
      { name: "Mystic Arcanum (9th level)", level: 17 },
      { name: "Ability Score Improvement", level: 19 },
      { name: "Eldritch Master", level: 20 },
    ],
  },
  {
    name: "Wizard",
    hitDie: 6,
    savingThrowProficiencies: ["intelligence", "wisdom"],
    spellcastingAbility: "intelligence",
    casterProgression: "full",
    features: [
      { name: "Spellcasting", level: 1 },
      { name: "Arcane Recovery", level: 1 },
      { name: "Arcane Tradition", level: 2 },
      { name: "Ability Score Improvement", level: 4 },
      { name: "Ability Score Improvement", level: 8 },
      { name: "Ability Score Improvement", level: 12 },
      { name: "Ability Score Improvement", level: 16 },
      { name: "Spell Mastery", level: 18 },
      { name: "Ability Score Improvement", level: 19 },
      { name: "Signature Spells", level: 20 },
    ],
  },
];
