// One-line, paraphrased-not-verbatim summaries of every class/subclass
// feature name appearing in classes.ts and subclasses.ts — purely a
// display convenience for the level-up wizard's "what did I just gain"
// step (ClassFeature itself stays {name, level}, matching every other
// consumer's needs, so this lives as a separate lookup rather than a new
// field every feature entry would otherwise have to carry). Keyed by the
// EXACT feature name string used in those two files; featureDescription()
// falls back to a generic line for any name that isn't here (defensive —
// every current name IS covered, but a future data addition that forgets
// to add a blurb still renders something sensible instead of blank).
export const FEATURE_DESCRIPTIONS: Record<string, string> = {
  "Ability Score Improvement": "Increase one ability score by 2, or two different ability scores by 1 each.",
  "Action Surge": "Take one additional action on your turn, once per short or long rest.",
  "Action Surge (2 uses)": "Action Surge can now be used twice between rests (only once per turn).",
  "Additional Fighting Style": "Learn a second Fighting Style option.",
  "Additional Magical Secrets": "Learn two more spells from any class's spell list.",
  "Arcane Recovery": "Once per day, recover expended spell slots during a short rest.",
  "Arcane Tradition": "Choose a school of magic to specialize in.",
  Archdruid: "Cast spells without expending a spell slot, at will.",
  "Aura of Courage": "You and nearby allies can't be frightened while you're conscious.",
  "Aura of Devotion": "You and nearby allies can't be charmed while you're conscious.",
  "Aura of Protection": "Add your Charisma modifier to your and nearby allies' saving throws.",
  "Bard College": "Choose a college that shapes your bardic talents.",
  "Bardic Inspiration": "Give an ally a bonus die to add to one ability check, attack roll, or saving throw.",
  "Beast Spells": "Cast many spells while in Wild Shape form.",
  "Blessed Healer": "Your healing spells also heal a small amount of HP on yourself.",
  Blindsense: "Sense any hidden or invisible creature within 10 feet.",
  "Bonus Cantrip": "Learn one additional druid cantrip.",
  "Bonus Proficiencies": "Gain proficiency in three skills of your choice.",
  "Bonus Proficiency": "Gain proficiency with heavy armor.",
  "Brutal Critical": "Roll one additional weapon damage die on a critical hit.",
  "Channel Divinity": "Channel divine energy to fuel magical effects, once per rest.",
  "Channel Divinity: Preserve Life": "Channel Divinity to restore a pool of hit points across nearby creatures.",
  "Channel Divinity: Sacred Weapon": "Channel Divinity to imbue a weapon with radiant power and a to-hit bonus.",
  "Channel Divinity: Turn the Unholy": "Channel Divinity to force fiends and undead to flee.",
  "Circle Spells": "Always have certain nature spells prepared, tied to your chosen land.",
  "Cleansing Touch": "Expend a spell slot to end one spell affecting you or a willing creature.",
  Countercharm: "Use your performance to grant nearby allies protection from being charmed or frightened.",
  "Cunning Action": "Take the Dash, Disengage, or Hide action as a bonus action.",
  "Cutting Words": "Expend Bardic Inspiration to weaken a nearby creature's roll.",
  "Danger Sense": "Advantage on Dexterity saves against effects you can see, like traps and spells.",
  "Dark One's Blessing": "Gain temporary hit points when you reduce a hostile creature to 0 HP.",
  "Dark One's Own Luck": "Add a bonus to one ability check or saving throw, once per rest.",
  "Defensive Tactics": "Choose a tactic for handling groups of enemies more safely.",
  "Deflect Missiles": "Reduce damage from a ranged weapon attack, and sometimes catch and throw it back.",
  "Destroy Undead": "Undead of low enough challenge rating are destroyed instead of turned.",
  "Diamond Soul": "Proficiency in all saving throws; spend Ki to reroll a failed save.",
  "Disciple of Life": "Your healing spells restore extra hit points.",
  "Divine Domain": "Choose a divine domain related to your deity, granting domain spells and features.",
  "Divine Health": "Immunity to disease.",
  "Divine Intervention": "Call on your deity to directly intervene on your behalf, once per week.",
  "Divine Sense": "Detect the presence of celestials, fiends, and undead nearby.",
  "Divine Smite": "Expend a spell slot to deal extra radiant damage on a melee hit.",
  "Divine Strike": "Deal extra radiant damage once per turn on a weapon hit.",
  "Draconic Presence": "Spend Sorcery Points to exude an aura of awe or fear.",
  "Draconic Resilience": "Extra hit points, and unarmored AC boosted by your draconic heritage.",
  "Dragon Ancestor": "Choose a dragon type tied to your bloodline, granting a related damage resistance later.",
  "Dragon Wings": "Sprout draconic wings, granting a flying speed.",
  "Druid Circle": "Choose a circle of like-minded druids, granting circle spells and features.",
  Druidic: "Know the secret language of druids and can leave hidden messages.",
  "Eldritch Invocations": "Learn eldritch invocations that grant magical customizations and abilities.",
  "Eldritch Master": "Draw on your patron's power to regain all expended Pact Magic slots.",
  "Elemental Affinity": "Add your Charisma modifier to one damage roll of your draconic damage type.",
  Elusive: "No attack roll has advantage against you while you aren't incapacitated.",
  "Empowered Evocation": "Add your Intelligence modifier to the damage of your evocation spells.",
  "Empty Body": "Spend Ki to become invisible, or to cast Astral Projection.",
  Evasion: "Take no damage on a successful Dexterity save that normally halves damage, half on a failure.",
  "Evocation Savant": "Halve the gold and time cost to copy an evocation spell into your spellbook.",
  Expertise: "Double your proficiency bonus for two chosen skill or tool proficiencies.",
  "Extra Attack": "Attack twice, instead of once, whenever you take the Attack action.",
  "Extra Attack (2)": "Attack three times, instead of once, whenever you take the Attack action.",
  "Extra Attack (3)": "Attack four times, instead of once, whenever you take the Attack action.",
  "Fast Hands": "Use Cunning Action to Sleight of Hand, disarm traps, or open locks as a bonus action.",
  "Fast Movement": "Your speed increases by 10 feet while not wearing heavy armor.",
  "Favored Enemy": "Choose a type of favored enemy, gaining bonuses to tracking and recalling information about it.",
  "Feral Instinct": "Advantage on initiative rolls, and act normally even if surprised while raging.",
  "Feral Senses": "Sense the location of invisible creatures within 30 feet.",
  "Fiendish Resilience": "Choose a damage type to resist after a short or long rest.",
  "Fighting Style": "Adopt a style of fighting as your specialty.",
  "Foe Slayer": "Add your Wisdom modifier to an attack roll or damage roll against your favored enemy.",
  "Font of Inspiration": "Regain all uses of Bardic Inspiration on a short or long rest.",
  "Font of Magic": "Gain Sorcery Points to fuel Metamagic and to create spell slots.",
  Frenzy: "Make a bonus-action melee attack while raging, at the cost of exhaustion when the rage ends.",
  "Hide in Plain Sight": "Camouflage yourself, becoming very hard to spot while remaining still.",
  "Holy Nimbus": "Emanate sunlight that damages fiends and undead and grants advantage against their spells.",
  "Hunter's Prey": "Choose a combat option for excelling against a single powerful foe or a horde of weaker ones.",
  "Hurl Through Hell": "Instantly banish a creature you hit to a hellish plane, dealing psychic damage.",
  "Improved Critical": "Score a critical hit on a roll of 19 or 20.",
  "Improved Divine Smite": "Your melee weapon hits deal extra radiant damage automatically.",
  Indomitable: "Reroll a failed saving throw, once per long rest.",
  "Indomitable Might": "Your Strength check total is never less than your Strength score.",
  "Intimidating Presence": "Frighten a creature with a terrifying display, as an action.",
  "Jack of All Trades": "Add half your proficiency bonus to any ability check that doesn't already include it.",
  Ki: "Gain Ki points to fuel Flurry of Blows, Patient Defense, and Step of the Wind.",
  "Ki-Empowered Strikes": "Your unarmed strikes count as magical for overcoming resistance and immunity.",
  "Land's Stride": "Move through nonmagical difficult terrain without extra cost, and resist magical plant effects.",
  "Lay on Hands": "A pool of healing power you can touch onto a creature to restore hit points or cure ailments.",
  "Magical Secrets": "Learn two spells from any class's spell list.",
  "Martial Archetype": "Choose an archetype that reflects your fighting style and training.",
  "Martial Arts": "Use Dexterity for unarmed strikes and monk weapons, and make a bonus-action unarmed strike.",
  Metamagic: "Learn options to twist your spells to suit your needs, at the cost of Sorcery Points.",
  "Mindless Rage": "Can't be charmed or frightened while raging.",
  "Monastic Tradition": "Choose a monastic tradition that shapes your ki and training.",
  Multiattack: "Choose an option for attacking multiple foes or making an extra attack.",
  "Mystic Arcanum (6th level)": "Learn one 6th-level spell you can cast once per long rest without a spell slot.",
  "Mystic Arcanum (7th level)": "Learn one 7th-level spell you can cast once per long rest without a spell slot.",
  "Mystic Arcanum (8th level)": "Learn one 8th-level spell you can cast once per long rest without a spell slot.",
  "Mystic Arcanum (9th level)": "Learn one 9th-level spell you can cast once per long rest without a spell slot.",
  "Natural Explorer": "Gain expertise in exploring and surviving your favored terrain.",
  "Natural Recovery": "Recover some expended spell slots during a short rest, once per day.",
  "Nature's Sanctuary": "Beasts and plant creatures are reluctant to attack you.",
  "Nature's Ward": "Immune to poison and disease, and can't be charmed or frightened by nature spirits.",
  "Oath Spells": "Always have certain spells related to your paladin oath prepared.",
  "Open Hand Technique": "Your Flurry of Blows hits can knock a creature prone, push it, or deny its reactions.",
  "Otherworldly Patron": "Choose an otherworldly patron who grants you power in exchange for service.",
  Overchannel: "Deal maximum damage with a spell, at the risk of taking necrotic damage yourself.",
  "Pact Boon": "Choose a boon from your patron: a bonded weapon, a servant, or a magical tome.",
  "Pact Magic": "Cast spells using your own small pool of spell slots that recharge on a short rest.",
  "Peerless Skill": "Add Bardic Inspiration to your own ability checks.",
  "Perfect Self": "Regain a minimum amount of Ki points if you roll initiative with none left.",
  "Persistent Rage": "Your rage only ends early if you fall unconscious or choose to end it.",
  "Potent Cantrip": "Creatures that succeed on a save against your cantrips still take half damage.",
  "Primal Champion": "Your Strength and Constitution scores increase, and their maximum rises.",
  "Primal Path": "Choose a path that shapes the nature of your rage.",
  "Primeval Awareness": "Expend a spell slot to sense certain types of creatures nearby.",
  "Purity of Body": "Immune to disease and poison.",
  "Purity of Spirit": "You are always under the effect of a Protection from Evil and Good spell.",
  "Quivering Palm": "Set up lethal vibrations in a creature that you can trigger to devastating effect later.",
  Rage: "Fly into a rage as a bonus action, gaining a damage bonus and resistance to physical damage.",
  "Ranger Archetype": "Choose an archetype that reflects your training as a ranger.",
  "Reckless Attack": "Attack with advantage at the cost of granting advantage to attacks against you.",
  "Relentless Rage": "Stay at 1 hit point instead of dropping to 0 while raging, with a rising cost to do so again.",
  "Reliable Talent": "Treat any ability check roll of 9 or lower as a 10, for skills you're proficient in.",
  "Remarkable Athlete": "Add half your proficiency bonus to Strength/Dexterity/Constitution checks that lack it.",
  Retaliation: "Make a melee attack as a reaction against a creature that damages you within reach.",
  "Roguish Archetype": "Choose an archetype that reflects your specialty as a rogue.",
  "Sacred Oath": "Swear a sacred oath that grants oath spells and channel divinity options.",
  "Sculpt Spells": "Protect chosen allies from the area of your own evocation spells.",
  "Second Wind": "Regain a small amount of hit points as a bonus action, once per short or long rest.",
  "Second-Story Work": "Climbing no longer costs extra movement, and your running jump distance increases.",
  "Signature Spells": "Choose two 3rd-level spells you can always cast once each without a spell slot.",
  "Slippery Mind": "Gain proficiency in Wisdom saving throws.",
  "Slow Fall": "Use your reaction to reduce falling damage.",
  "Sneak Attack": "Deal extra damage once per turn to a target you have advantage against or an ally threatens.",
  "Song of Rest": "You and allies who rest near your music regain extra hit points during a short rest.",
  "Sorcerous Origin": "Choose the source of your innate magic.",
  "Sorcerous Restoration": "Regain 4 expended Sorcery Points whenever you finish a short rest.",
  "Spell Mastery": "Cast one 1st-level and one 2nd-level spell at will, without expending a spell slot.",
  Spellcasting: "Cast spells using this class's spell list and spellcasting ability.",
  "Stillness of Mind": "Use your action to end one effect on yourself causing you to be charmed or frightened.",
  "Stroke of Luck": "Turn a failed attack roll or ability check into a success, once per short or long rest.",
  "Stunning Strike": "Spend a Ki point to attempt to stun a creature you hit with a melee weapon attack.",
  "Superior Critical": "Score a critical hit on a roll of 18-20.",
  "Superior Hunter's Defense": "Choose a defensive option to use as a reaction when a creature hits you.",
  "Superior Inspiration": "Regain one expended use of Bardic Inspiration when you roll initiative with none left.",
  "Supreme Healing": "Your healing spells restore the maximum possible number of hit points instead of rolling.",
  "Supreme Sneak": "Advantage on Stealth checks if you move no more than half your speed on the same turn.",
  Survivor: "Regain hit points at the start of each of your turns if you're badly wounded.",
  "Thief's Reflexes": "Take two turns during the first round of combat.",
  "Thieves' Cant": "Know a secret mix of dialect, jargon, and code understood only by other rogues.",
  "Timeless Body": "Age more slowly, and (for druids) never suffer the frailty of old age.",
  "Tongue of the Sun and Moon": "Understand all spoken languages, and be understood by any creature that has one.",
  Tranquility: "Project an aura of peace, warding off charms, that lingers briefly after combat.",
  "Unarmored Defense": "Add an extra ability modifier to your AC while not wearing armor.",
  "Unarmored Movement": "Your speed increases while you aren't wearing armor or wielding a shield.",
  "Uncanny Dodge": "Use your reaction to halve the damage from an attack that hits you.",
  "Use Magic Device": "Ignore class, race, and level requirements on the use of magic items.",
  Vanish: "Hide as a bonus action, and can't be tracked by nonmagical means while not heavily encumbered.",
  "Wholeness of Body": "Use your action to heal yourself a modest amount of hit points, once per long rest.",
  "Wild Shape": "Magically transform into a beast you have seen before, for a limited time.",
};

/** Falls back to a generic, still-informative line for any feature name
 * not in the lookup above — defensive against a future data addition that
 * forgets to add a blurb, never a blank display. */
export function featureDescription(name: string): string {
  return FEATURE_DESCRIPTIONS[name] ?? `A ${name} feature granted by your class.`;
}
