import type { Spell, SpellLevel, SpellRange, SpellSchool, TargetType } from "./types";

type SpellTuple = [
  name: string,
  level: SpellLevel,
  school: SpellSchool,
  range: SpellRange,
  targetType: TargetType,
  concentration: boolean,
];

const SPELL_TUPLES: SpellTuple[] = [
  // Level 0 (cantrips)
  ["Acid Splash", 0, "conjuration", 60, "point", false],
  ["Blade Ward", 0, "abjuration", "self", "self", false],
  ["Chill Touch", 0, "necromancy", 120, "single", false],
  ["Dancing Lights", 0, "evocation", 120, "point", true],
  ["Druidcraft", 0, "transmutation", 30, "point", false],
  ["Eldritch Blast", 0, "evocation", 120, "single", false],
  ["Fire Bolt", 0, "evocation", 120, "single", false],
  ["Friends", 0, "enchantment", "self", "single", true],
  ["Guidance", 0, "divination", "touch", "single", true],
  ["Light", 0, "evocation", "touch", "single", false],
  ["Mage Hand", 0, "conjuration", 30, "point", false],
  ["Mending", 0, "transmutation", "touch", "single", false],
  ["Message", 0, "transmutation", 120, "single", false],
  ["Minor Illusion", 0, "illusion", 30, "point", false],
  ["Poison Spray", 0, "conjuration", 10, "single", false],
  ["Prestidigitation", 0, "transmutation", 10, "point", false],
  ["Produce Flame", 0, "conjuration", "self", "self", false],
  ["Ray of Frost", 0, "evocation", 60, "single", false],
  ["Resistance", 0, "abjuration", "touch", "single", true],
  ["Sacred Flame", 0, "evocation", 60, "single", false],
  ["Shillelagh", 0, "transmutation", "touch", "self", false],
  ["Shocking Grasp", 0, "evocation", "touch", "single", false],
  ["Spare the Dying", 0, "necromancy", "touch", "single", false],
  ["Thaumaturgy", 0, "transmutation", 30, "point", false],
  ["True Strike", 0, "divination", 30, "single", true],
  ["Vicious Mockery", 0, "enchantment", 60, "single", false],

  // Level 1
  ["Alarm", 1, "abjuration", 30, "area", false],
  ["Animal Friendship", 1, "enchantment", 30, "single", false],
  ["Bane", 1, "enchantment", 30, "area", true],
  ["Bless", 1, "enchantment", 30, "area", true],
  ["Burning Hands", 1, "evocation", "self", "area", false],
  ["Charm Person", 1, "enchantment", 30, "single", false],
  ["Chromatic Orb", 1, "evocation", 90, "single", false],
  ["Color Spray", 1, "illusion", "self", "area", false],
  ["Command", 1, "enchantment", 60, "single", false],
  ["Comprehend Languages", 1, "divination", "self", "self", false],
  ["Compelled Duel", 1, "abjuration", 30, "single", true],
  ["Create or Destroy Water", 1, "transmutation", 30, "point", false],
  ["Cure Wounds", 1, "evocation", "touch", "single", false],
  ["Detect Evil and Good", 1, "divination", "self", "self", true],
  ["Detect Magic", 1, "divination", "self", "self", true],
  ["Detect Poison and Disease", 1, "divination", "self", "self", true],
  ["Disguise Self", 1, "illusion", "self", "self", false],
  ["Dissonant Whispers", 1, "enchantment", 60, "single", false],
  ["Divine Favor", 1, "evocation", "self", "self", false],
  ["Entangle", 1, "conjuration", 90, "area", true],
  ["Expeditious Retreat", 1, "transmutation", "self", "self", true],
  ["Faerie Fire", 1, "evocation", 60, "area", true],
  ["False Life", 1, "necromancy", "self", "self", false],
  ["Feather Fall", 1, "transmutation", 60, "single", false],
  ["Find Familiar", 1, "conjuration", 10, "point", false],
  ["Fog Cloud", 1, "conjuration", 120, "area", true],
  ["Goodberry", 1, "transmutation", "touch", "point", false],
  ["Grease", 1, "conjuration", 60, "area", false],
  ["Guiding Bolt", 1, "evocation", 120, "single", false],
  ["Healing Word", 1, "evocation", 60, "single", false],
  ["Heroism", 1, "enchantment", "touch", "single", true],
  ["Hex", 1, "enchantment", 90, "single", true],
  ["Hunter's Mark", 1, "divination", 90, "single", true],
  ["Identify", 1, "divination", "touch", "single", false],
  ["Illusory Script", 1, "illusion", "touch", "point", false],
  ["Inflict Wounds", 1, "necromancy", "touch", "single", false],
  ["Jump", 1, "transmutation", "touch", "single", false],
  ["Longstrider", 1, "transmutation", "touch", "single", false],
  ["Mage Armor", 1, "abjuration", "touch", "single", false],
  ["Magic Missile", 1, "evocation", 120, "single", false],
  ["Protection from Evil and Good", 1, "abjuration", "touch", "single", true],
  ["Purify Food and Drink", 1, "transmutation", 10, "area", false],
  ["Ray of Sickness", 1, "necromancy", 60, "single", false],
  ["Sanctuary", 1, "abjuration", 30, "single", false],
  ["Searing Smite", 1, "evocation", "self", "self", true],
  ["Shield", 1, "abjuration", "self", "self", false],
  ["Shield of Faith", 1, "abjuration", 60, "single", true],
  ["Silent Image", 1, "illusion", 60, "area", true],
  ["Sleep", 1, "enchantment", 90, "area", true],
  ["Speak with Animals", 1, "divination", "self", "self", false],
  ["Hideous Laughter", 1, "enchantment", 30, "single", true],
  ["Floating Disk", 1, "conjuration", 30, "point", false],
  ["Thunderous Smite", 1, "evocation", "self", "self", false],
  ["Thunderwave", 1, "evocation", "self", "area", false],
  ["Unseen Servant", 1, "conjuration", 60, "point", false],
  ["Witch Bolt", 1, "evocation", 30, "single", true],
  ["Wrathful Smite", 1, "evocation", "self", "self", true],
  ["Ensnaring Strike", 1, "conjuration", "self", "single", true],

  // Level 2
  ["Aid", 2, "abjuration", 30, "area", false],
  ["Alter Self", 2, "transmutation", "self", "self", true],
  ["Animal Messenger", 2, "enchantment", 30, "single", false],
  ["Arcane Lock", 2, "abjuration", "touch", "point", false],
  ["Augury", 2, "divination", "self", "self", false],
  ["Barkskin", 2, "transmutation", "touch", "single", true],
  ["Beast Sense", 2, "divination", "touch", "self", true],
  ["Blindness/Deafness", 2, "necromancy", 30, "single", false],
  ["Blur", 2, "illusion", "self", "self", true],
  ["Branding Smite", 2, "evocation", "self", "single", true],
  ["Continual Flame", 2, "evocation", "touch", "point", false],
  ["Crown of Madness", 2, "enchantment", 120, "single", true],
  ["Darkness", 2, "evocation", 60, "point", true],
  ["Darkvision", 2, "transmutation", "touch", "single", false],
  ["Detect Thoughts", 2, "divination", "self", "single", true],
  ["Enhance Ability", 2, "transmutation", "touch", "single", true],
  ["Enlarge/Reduce", 2, "transmutation", 30, "single", true],
  ["Enthrall", 2, "enchantment", 60, "area", false],
  ["Find Steed", 2, "conjuration", 30, "point", false],
  ["Find Traps", 2, "divination", 120, "point", false],
  ["Flame Blade", 2, "evocation", "self", "self", true],
  ["Flaming Sphere", 2, "conjuration", 60, "area", true],
  ["Gentle Repose", 2, "necromancy", "touch", "single", false],
  ["Gust of Wind", 2, "evocation", "self", "area", true],
  ["Heat Metal", 2, "transmutation", 60, "single", true],
  ["Hold Person", 2, "enchantment", 60, "single", true],
  ["Invisibility", 2, "illusion", "touch", "single", true],
  ["Knock", 2, "transmutation", 60, "point", false],
  ["Lesser Restoration", 2, "abjuration", "touch", "single", false],
  ["Levitate", 2, "transmutation", 60, "single", true],
  ["Locate Animals or Plants", 2, "divination", "self", "self", false],
  ["Locate Object", 2, "divination", "self", "self", true],
  ["Magic Mouth", 2, "illusion", 30, "point", false],
  ["Magic Weapon", 2, "transmutation", "touch", "single", false],
  ["Mirror Image", 2, "illusion", "self", "self", false],
  ["Misty Step", 2, "conjuration", "self", "self", false],
  ["Moonbeam", 2, "evocation", 120, "area", true],
  ["Pass without Trace", 2, "abjuration", "self", "self", true],
  ["Prayer of Healing", 2, "evocation", 30, "area", false],
  ["Protection from Poison", 2, "abjuration", "touch", "single", false],
  ["Ray of Enfeeblement", 2, "necromancy", 60, "single", true],
  ["Rope Trick", 2, "transmutation", "touch", "point", false],
  ["Scorching Ray", 2, "evocation", 120, "single", false],
  ["See Invisibility", 2, "divination", "self", "self", false],
  ["Shatter", 2, "evocation", 60, "area", false],
  ["Silence", 2, "illusion", 120, "area", true],
  ["Spider Climb", 2, "transmutation", "touch", "single", true],
  ["Spike Growth", 2, "transmutation", 150, "area", true],
  ["Spiritual Weapon", 2, "evocation", 60, "single", false],
  ["Suggestion", 2, "enchantment", 30, "single", true],
  ["Warding Bond", 2, "abjuration", "touch", "single", false],
  ["Web", 2, "conjuration", 60, "area", true],
  ["Zone of Truth", 2, "enchantment", 60, "area", false],
  ["Acid Arrow", 2, "evocation", 90, "single", false],

  // Level 3
  ["Animate Dead", 3, "necromancy", 10, "point", false],
  ["Bestow Curse", 3, "necromancy", "touch", "single", true],
  ["Blink", 3, "transmutation", "self", "self", false],
  ["Call Lightning", 3, "conjuration", 120, "area", true],
  ["Clairvoyance", 3, "divination", 1000, "point", true],
  ["Conjure Animals", 3, "conjuration", 60, "area", true],
  ["Counterspell", 3, "abjuration", 60, "single", false],
  ["Create Food and Water", 3, "conjuration", 30, "point", false],
  ["Daylight", 3, "evocation", 60, "point", false],
  ["Dispel Magic", 3, "abjuration", 120, "single", false],
  ["Elemental Weapon", 3, "transmutation", "touch", "single", true],
  ["Fear", 3, "illusion", "self", "area", true],
  ["Feign Death", 3, "necromancy", "touch", "single", false],
  ["Fireball", 3, "evocation", 150, "area", false],
  ["Fly", 3, "transmutation", "touch", "single", true],
  ["Gaseous Form", 3, "transmutation", "touch", "single", true],
  ["Glyph of Warding", 3, "abjuration", "touch", "point", false],
  ["Haste", 3, "transmutation", 30, "single", true],
  ["Hunger of Hadar", 3, "conjuration", 150, "area", true],
  ["Hypnotic Pattern", 3, "illusion", 120, "area", true],
  ["Lightning Bolt", 3, "evocation", "self", "area", false],
  ["Magic Circle", 3, "abjuration", 10, "point", false],
  ["Major Image", 3, "illusion", 120, "area", true],
  ["Mass Healing Word", 3, "evocation", 60, "area", false],
  ["Meld into Stone", 3, "transmutation", "touch", "self", false],
  ["Nondetection", 3, "abjuration", "touch", "single", false],
  ["Plant Growth", 3, "transmutation", 150, "area", false],
  ["Protection from Energy", 3, "abjuration", "touch", "single", true],
  ["Remove Curse", 3, "abjuration", "touch", "single", false],
  ["Revivify", 3, "necromancy", "touch", "single", false],
  ["Sending", 3, "divination", 5000, "single", false],
  ["Sleet Storm", 3, "conjuration", 150, "area", true],
  ["Slow", 3, "transmutation", 120, "area", true],
  ["Speak with Dead", 3, "necromancy", 10, "single", false],
  ["Speak with Plants", 3, "transmutation", "self", "area", false],
  ["Spirit Guardians", 3, "conjuration", "self", "area", true],
  ["Stinking Cloud", 3, "conjuration", 90, "area", true],
  ["Tongues", 3, "divination", "touch", "single", false],
  ["Vampiric Touch", 3, "necromancy", "self", "single", true],
  ["Water Breathing", 3, "transmutation", 30, "area", false],
  ["Water Walk", 3, "transmutation", 30, "area", false],
  ["Wind Wall", 3, "evocation", 120, "area", true],

  // Level 4
  ["Arcane Eye", 4, "divination", 30, "point", true],
  ["Aura of Life", 4, "abjuration", "self", "area", true],
  ["Aura of Purity", 4, "abjuration", "self", "area", true],
  ["Banishment", 4, "abjuration", 60, "single", true],
  ["Blight", 4, "necromancy", 30, "single", false],
  ["Compulsion", 4, "enchantment", 30, "single", true],
  ["Confusion", 4, "enchantment", 90, "area", true],
  ["Conjure Minor Elementals", 4, "conjuration", 90, "area", true],
  ["Conjure Woodland Beings", 4, "conjuration", 60, "area", true],
  ["Control Water", 4, "transmutation", 300, "area", true],
  ["Death Ward", 4, "abjuration", "touch", "single", false],
  ["Dimension Door", 4, "conjuration", 500, "self", false],
  ["Divination", 4, "divination", "self", "self", false],
  ["Dominate Beast", 4, "enchantment", 60, "single", true],
  ["Fabricate", 4, "transmutation", 120, "point", false],
  ["Faithful Hound", 4, "conjuration", 30, "point", false],
  ["Fire Shield", 4, "evocation", "self", "self", false],
  ["Freedom of Movement", 4, "abjuration", "touch", "single", false],
  ["Giant Insect", 4, "transmutation", 30, "area", true],
  ["Grasping Vine", 4, "conjuration", 30, "point", true],
  ["Greater Invisibility", 4, "illusion", "touch", "single", true],
  ["Guardian of Faith", 4, "conjuration", 30, "point", false],
  ["Hallucinatory Terrain", 4, "illusion", 300, "area", false],
  ["Ice Storm", 4, "evocation", 300, "area", false],
  ["Locate Creature", 4, "divination", "self", "self", true],
  ["Private Sanctum", 4, "abjuration", 120, "point", false],
  ["Resilient Sphere", 4, "evocation", 30, "single", true],
  ["Phantasmal Killer", 4, "illusion", 120, "single", true],
  ["Polymorph", 4, "transmutation", 60, "single", true],
  ["Stone Shape", 4, "transmutation", "touch", "point", false],
  ["Stoneskin", 4, "abjuration", "touch", "single", true],
  ["Wall of Fire", 4, "evocation", 120, "area", true],

  // Level 5
  ["Animate Objects", 5, "transmutation", 120, "area", true],
  ["Antilife Shell", 5, "abjuration", "self", "self", true],
  ["Awaken", 5, "transmutation", "touch", "single", false],
  ["Banishing Smite", 5, "abjuration", "self", "self", true],
  ["Arcane Hand", 5, "evocation", 120, "point", true],
  ["Circle of Power", 5, "abjuration", "self", "area", true],
  ["Cloudkill", 5, "conjuration", 120, "area", true],
  ["Commune", 5, "divination", "self", "self", false],
  ["Commune with Nature", 5, "divination", "self", "self", false],
  ["Cone of Cold", 5, "evocation", "self", "area", false],
  ["Conjure Elemental", 5, "conjuration", 90, "area", true],
  ["Contact Other Plane", 5, "divination", "self", "self", false],
  ["Contagion", 5, "necromancy", "touch", "single", false],
  ["Creation", 5, "illusion", 30, "point", false],
  ["Destructive Wave", 5, "evocation", "self", "area", false],
  ["Dispel Evil and Good", 5, "abjuration", "self", "self", true],
  ["Dominate Person", 5, "enchantment", 60, "single", true],
  ["Dream", 5, "illusion", 5000, "single", true],
  ["Flame Strike", 5, "evocation", 60, "area", false],
  ["Geas", 5, "enchantment", 60, "single", false],
  ["Greater Restoration", 5, "abjuration", "touch", "single", false],
  ["Hallow", 5, "evocation", "touch", "point", false],
  ["Hold Monster", 5, "enchantment", 90, "single", true],
  ["Insect Plague", 5, "conjuration", 300, "area", true],
  ["Legend Lore", 5, "divination", "self", "self", false],
  ["Mass Cure Wounds", 5, "evocation", 60, "area", false],
  ["Modify Memory", 5, "enchantment", 30, "single", true],
  ["Passwall", 5, "transmutation", "touch", "point", false],
  ["Planar Binding", 5, "abjuration", 60, "single", false],
  ["Raise Dead", 5, "necromancy", "touch", "single", false],
  ["Telepathic Bond", 5, "divination", 30, "area", false],
  ["Reincarnate", 5, "transmutation", "touch", "single", false],
  ["Scrying", 5, "divination", "self", "single", true],
  ["Seeming", 5, "illusion", 30, "area", false],
  ["Swift Quiver", 5, "transmutation", 60, "single", true],
  ["Telekinesis", 5, "transmutation", 60, "single", true],
  ["Teleportation Circle", 5, "conjuration", 10, "point", false],
  ["Tree Stride", 5, "transmutation", "self", "self", true],
  ["Wall of Force", 5, "evocation", 120, "area", true],
  ["Wall of Stone", 5, "evocation", 120, "area", true],

  // Level 6
  ["Arcane Gate", 6, "conjuration", 500, "point", true],
  ["Blade Barrier", 6, "evocation", 90, "area", true],
  ["Chain Lightning", 6, "evocation", 150, "area", false],
  ["Circle of Death", 6, "necromancy", 150, "area", false],
  ["Conjure Fey", 6, "conjuration", 90, "area", true],
  ["Contingency", 6, "transmutation", "self", "self", false],
  ["Create Undead", 6, "necromancy", 10, "point", false],
  ["Disintegrate", 6, "transmutation", 60, "single", false],
  ["Instant Summons", 6, "conjuration", "touch", "point", false],
  ["Eyebite", 6, "necromancy", "self", "single", true],
  ["Find the Path", 6, "divination", "self", "self", true],
  ["Flesh to Stone", 6, "transmutation", 60, "single", true],
  ["Forbiddance", 6, "abjuration", "touch", "area", false],
  ["Globe of Invulnerability", 6, "abjuration", "self", "self", true],
  ["Guards and Wards", 6, "abjuration", "touch", "point", false],
  ["Harm", 6, "necromancy", 60, "single", false],
  ["Heal", 6, "evocation", 60, "single", false],
  ["Heroes' Feast", 6, "conjuration", 30, "point", false],
  ["Magic Jar", 6, "necromancy", "self", "single", false],
  ["Mass Suggestion", 6, "enchantment", 60, "single", false],
  ["Move Earth", 6, "transmutation", 120, "area", true],
  ["Freezing Sphere", 6, "evocation", 300, "area", false],
  ["Irresistible Dance", 6, "enchantment", 30, "single", true],
  ["Planar Ally", 6, "conjuration", 60, "single", false],
  ["Programmed Illusion", 6, "illusion", 120, "point", false],
  ["Sunbeam", 6, "evocation", "self", "area", true],
  ["Transport via Plants", 6, "conjuration", 10, "point", false],
  ["True Seeing", 6, "divination", "touch", "single", false],
  ["Wall of Ice", 6, "evocation", 120, "area", true],
  ["Wind Walk", 6, "transmutation", 30, "area", false],
  ["Word of Recall", 6, "conjuration", "touch", "self", false],

  // Level 7
  ["Conjure Celestial", 7, "conjuration", 90, "area", true],
  ["Delayed Blast Fireball", 7, "evocation", 150, "area", true],
  ["Divine Word", 7, "evocation", 30, "area", false],
  ["Etherealness", 7, "transmutation", "self", "self", false],
  ["Finger of Death", 7, "necromancy", 60, "single", false],
  ["Fire Storm", 7, "evocation", 150, "area", false],
  ["Forcecage", 7, "evocation", 100, "area", false],
  ["Mirage Arcane", 7, "illusion", "self", "area", false],
  ["Magnificent Mansion", 7, "conjuration", 300, "point", false],
  ["Arcane Sword", 7, "evocation", 60, "single", true],
  ["Plane Shift", 7, "conjuration", "touch", "single", false],
  ["Prismatic Spray", 7, "evocation", "self", "area", false],
  ["Project Image", 7, "illusion", 500, "single", true],
  ["Regenerate", 7, "transmutation", "touch", "single", false],
  ["Resurrection", 7, "necromancy", "touch", "single", false],
  ["Reverse Gravity", 7, "transmutation", 50, "area", true],
  ["Sequester", 7, "transmutation", "touch", "single", false],
  ["Simulacrum", 7, "illusion", "touch", "point", false],
  ["Symbol", 7, "abjuration", "touch", "point", false],
  ["Teleport", 7, "conjuration", 10, "point", false],

  // Level 8
  ["Animal Shapes", 8, "transmutation", 30, "area", false],
  ["Antimagic Field", 8, "abjuration", "self", "self", true],
  ["Antipathy/Sympathy", 8, "enchantment", 60, "point", false],
  ["Clone", 8, "necromancy", "touch", "single", false],
  ["Control Weather", 8, "transmutation", "self", "self", true],
  ["Demiplane", 8, "conjuration", 60, "point", false],
  ["Dominate Monster", 8, "enchantment", 60, "single", true],
  ["Earthquake", 8, "evocation", 500, "area", true],
  ["Feeblemind", 8, "enchantment", 150, "single", false],
  ["Glibness", 8, "enchantment", "self", "self", false],
  ["Holy Aura", 8, "abjuration", "self", "area", true],
  ["Incendiary Cloud", 8, "conjuration", 150, "area", true],
  ["Maze", 8, "conjuration", 60, "single", true],
  ["Mind Blank", 8, "abjuration", "touch", "single", false],
  ["Power Word Stun", 8, "enchantment", 60, "single", false],
  ["Sunburst", 8, "evocation", 150, "area", false],
  ["Telepathy", 8, "evocation", 5000, "single", false],
  ["Tsunami", 8, "conjuration", 500, "area", true],

  // Level 9
  ["Astral Projection", 9, "necromancy", "touch", "self", false],
  ["Foresight", 9, "divination", "touch", "single", false],
  ["Gate", 9, "conjuration", 60, "point", true],
  ["Imprisonment", 9, "abjuration", "touch", "single", false],
  ["Mass Heal", 9, "evocation", 60, "area", false],
  ["Meteor Swarm", 9, "evocation", 1000, "area", false],
  ["Power Word Kill", 9, "enchantment", 60, "single", false],
  ["Prismatic Wall", 9, "abjuration", 60, "area", false],
  ["Shapechange", 9, "transmutation", "self", "self", true],
  ["Storm of Vengeance", 9, "conjuration", 500, "area", true],
  ["Time Stop", 9, "transmutation", "self", "self", false],
  ["True Polymorph", 9, "transmutation", 30, "single", true],
  ["True Resurrection", 9, "necromancy", "touch", "single", false],
  ["Weird", 9, "illusion", 120, "area", true],
  ["Wish", 9, "conjuration", "self", "self", false],
];

export const SPELLS: Spell[] = SPELL_TUPLES.map(([name, level, school, range, targetType, concentration]) => ({
  name,
  level,
  school,
  range,
  targetType,
  concentration,
}));
