import type { ClassName, Spell, SpellAttack, SpellLevel, SpellRange, SpellSchool, TargetType } from "./types";

type SpellTuple = [
  name: string,
  level: SpellLevel,
  school: SpellSchool,
  range: SpellRange,
  targetType: TargetType,
  concentration: boolean,
];

const SPELL_TUPLES: SpellTuple[] = [
  // Level 0 (cantrips)
  ["Acid Splash", 0, "conjuration", 60, "point", false],
  ["Blade Ward", 0, "abjuration", "self", "self", false],
  ["Chill Touch", 0, "necromancy", 120, "single", false],
  ["Dancing Lights", 0, "evocation", 120, "point", true],
  ["Druidcraft", 0, "transmutation", 30, "point", false],
  ["Eldritch Blast", 0, "evocation", 120, "single", false],
  ["Fire Bolt", 0, "evocation", 120, "single", false],
  ["Friends", 0, "enchantment", "self", "single", true],
  ["Guidance", 0, "divination", "touch", "single", true],
  ["Light", 0, "evocation", "touch", "single", false],
  ["Mage Hand", 0, "conjuration", 30, "point", false],
  ["Mending", 0, "transmutation", "touch", "single", false],
  ["Message", 0, "transmutation", 120, "single", false],
  ["Minor Illusion", 0, "illusion", 30, "point", false],
  ["Poison Spray", 0, "conjuration", 10, "single", false],
  ["Prestidigitation", 0, "transmutation", 10, "point", false],
  ["Produce Flame", 0, "conjuration", "self", "self", false],
  ["Ray of Frost", 0, "evocation", 60, "single", false],
  ["Resistance", 0, "abjuration", "touch", "single", true],
  ["Sacred Flame", 0, "evocation", 60, "single", false],
  ["Shillelagh", 0, "transmutation", "touch", "self", false],
  ["Shocking Grasp", 0, "evocation", "touch", "single", false],
  ["Spare the Dying", 0, "necromancy", "touch", "single", false],
  ["Thaumaturgy", 0, "transmutation", 30, "point", false],
  ["True Strike", 0, "divination", 30, "single", true],
  ["Vicious Mockery", 0, "enchantment", 60, "single", false],

  // Level 1
  ["Alarm", 1, "abjuration", 30, "area", false],
  ["Animal Friendship", 1, "enchantment", 30, "single", false],
  ["Bane", 1, "enchantment", 30, "area", true],
  ["Bless", 1, "enchantment", 30, "area", true],
  ["Burning Hands", 1, "evocation", "self", "area", false],
  ["Charm Person", 1, "enchantment", 30, "single", false],
  ["Chromatic Orb", 1, "evocation", 90, "single", false],
  ["Color Spray", 1, "illusion", "self", "area", false],
  ["Command", 1, "enchantment", 60, "single", false],
  ["Comprehend Languages", 1, "divination", "self", "self", false],
  ["Compelled Duel", 1, "abjuration", 30, "single", true],
  ["Create or Destroy Water", 1, "transmutation", 30, "point", false],
  ["Cure Wounds", 1, "evocation", "touch", "single", false],
  ["Detect Evil and Good", 1, "divination", "self", "self", true],
  ["Detect Magic", 1, "divination", "self", "self", true],
  ["Detect Poison and Disease", 1, "divination", "self", "self", true],
  ["Disguise Self", 1, "illusion", "self", "self", false],
  ["Dissonant Whispers", 1, "enchantment", 60, "single", false],
  ["Divine Favor", 1, "evocation", "self", "self", false],
  ["Entangle", 1, "conjuration", 90, "area", true],
  ["Expeditious Retreat", 1, "transmutation", "self", "self", true],
  ["Faerie Fire", 1, "evocation", 60, "area", true],
  ["False Life", 1, "necromancy", "self", "self", false],
  ["Feather Fall", 1, "transmutation", 60, "single", false],
  ["Find Familiar", 1, "conjuration", 10, "point", false],
  ["Fog Cloud", 1, "conjuration", 120, "area", true],
  ["Goodberry", 1, "transmutation", "touch", "point", false],
  ["Grease", 1, "conjuration", 60, "area", false],
  ["Guiding Bolt", 1, "evocation", 120, "single", false],
  ["Healing Word", 1, "evocation", 60, "single", false],
  ["Heroism", 1, "enchantment", "touch", "single", true],
  ["Hex", 1, "enchantment", 90, "single", true],
  ["Hunter's Mark", 1, "divination", 90, "single", true],
  ["Identify", 1, "divination", "touch", "single", false],
  ["Illusory Script", 1, "illusion", "touch", "point", false],
  ["Inflict Wounds", 1, "necromancy", "touch", "single", false],
  ["Jump", 1, "transmutation", "touch", "single", false],
  ["Longstrider", 1, "transmutation", "touch", "single", false],
  ["Mage Armor", 1, "abjuration", "touch", "single", false],
  ["Magic Missile", 1, "evocation", 120, "single", false],
  ["Protection from Evil and Good", 1, "abjuration", "touch", "single", true],
  ["Purify Food and Drink", 1, "transmutation", 10, "area", false],
  ["Ray of Sickness", 1, "necromancy", 60, "single", false],
  ["Sanctuary", 1, "abjuration", 30, "single", false],
  ["Searing Smite", 1, "evocation", "self", "self", true],
  ["Shield", 1, "abjuration", "self", "self", false],
  ["Shield of Faith", 1, "abjuration", 60, "single", true],
  ["Silent Image", 1, "illusion", 60, "area", true],
  ["Sleep", 1, "enchantment", 90, "area", true],
  ["Speak with Animals", 1, "divination", "self", "self", false],
  ["Hideous Laughter", 1, "enchantment", 30, "single", true],
  ["Floating Disk", 1, "conjuration", 30, "point", false],
  ["Thunderous Smite", 1, "evocation", "self", "self", false],
  ["Thunderwave", 1, "evocation", "self", "area", false],
  ["Unseen Servant", 1, "conjuration", 60, "point", false],
  ["Witch Bolt", 1, "evocation", 30, "single", true],
  ["Wrathful Smite", 1, "evocation", "self", "self", true],
  ["Ensnaring Strike", 1, "conjuration", "self", "single", true],

  // Level 2
  ["Aid", 2, "abjuration", 30, "area", false],
  ["Alter Self", 2, "transmutation", "self", "self", true],
  ["Animal Messenger", 2, "enchantment", 30, "single", false],
  ["Arcane Lock", 2, "abjuration", "touch", "point", false],
  ["Augury", 2, "divination", "self", "self", false],
  ["Barkskin", 2, "transmutation", "touch", "single", true],
  ["Beast Sense", 2, "divination", "touch", "self", true],
  ["Blindness/Deafness", 2, "necromancy", 30, "single", false],
  ["Blur", 2, "illusion", "self", "self", true],
  ["Branding Smite", 2, "evocation", "self", "single", true],
  ["Continual Flame", 2, "evocation", "touch", "point", false],
  ["Crown of Madness", 2, "enchantment", 120, "single", true],
  ["Darkness", 2, "evocation", 60, "point", true],
  ["Darkvision", 2, "transmutation", "touch", "single", false],
  ["Detect Thoughts", 2, "divination", "self", "single", true],
  ["Enhance Ability", 2, "transmutation", "touch", "single", true],
  ["Enlarge/Reduce", 2, "transmutation", 30, "single", true],
  ["Enthrall", 2, "enchantment", 60, "area", false],
  ["Find Steed", 2, "conjuration", 30, "point", false],
  ["Find Traps", 2, "divination", 120, "point", false],
  ["Flame Blade", 2, "evocation", "self", "self", true],
  ["Flaming Sphere", 2, "conjuration", 60, "area", true],
  ["Gentle Repose", 2, "necromancy", "touch", "single", false],
  ["Gust of Wind", 2, "evocation", "self", "area", true],
  ["Heat Metal", 2, "transmutation", 60, "single", true],
  ["Hold Person", 2, "enchantment", 60, "single", true],
  ["Invisibility", 2, "illusion", "touch", "single", true],
  ["Knock", 2, "transmutation", 60, "point", false],
  ["Lesser Restoration", 2, "abjuration", "touch", "single", false],
  ["Levitate", 2, "transmutation", 60, "single", true],
  ["Locate Animals or Plants", 2, "divination", "self", "self", false],
  ["Locate Object", 2, "divination", "self", "self", true],
  ["Magic Mouth", 2, "illusion", 30, "point", false],
  ["Magic Weapon", 2, "transmutation", "touch", "single", false],
  ["Mirror Image", 2, "illusion", "self", "self", false],
  ["Misty Step", 2, "conjuration", "self", "self", false],
  ["Moonbeam", 2, "evocation", 120, "area", true],
  ["Pass without Trace", 2, "abjuration", "self", "self", true],
  ["Prayer of Healing", 2, "evocation", 30, "area", false],
  ["Protection from Poison", 2, "abjuration", "touch", "single", false],
  ["Ray of Enfeeblement", 2, "necromancy", 60, "single", true],
  ["Rope Trick", 2, "transmutation", "touch", "point", false],
  ["Scorching Ray", 2, "evocation", 120, "single", false],
  ["See Invisibility", 2, "divination", "self", "self", false],
  ["Shatter", 2, "evocation", 60, "area", false],
  ["Silence", 2, "illusion", 120, "area", true],
  ["Spider Climb", 2, "transmutation", "touch", "single", true],
  ["Spike Growth", 2, "transmutation", 150, "area", true],
  ["Spiritual Weapon", 2, "evocation", 60, "single", false],
  ["Suggestion", 2, "enchantment", 30, "single", true],
  ["Warding Bond", 2, "abjuration", "touch", "single", false],
  ["Web", 2, "conjuration", 60, "area", true],
  ["Zone of Truth", 2, "enchantment", 60, "area", false],
  ["Acid Arrow", 2, "evocation", 90, "single", false],

  // Level 3
  ["Animate Dead", 3, "necromancy", 10, "point", false],
  ["Bestow Curse", 3, "necromancy", "touch", "single", true],
  ["Blink", 3, "transmutation", "self", "self", false],
  ["Call Lightning", 3, "conjuration", 120, "area", true],
  ["Clairvoyance", 3, "divination", 1000, "point", true],
  ["Conjure Animals", 3, "conjuration", 60, "area", true],
  ["Counterspell", 3, "abjuration", 60, "single", false],
  ["Create Food and Water", 3, "conjuration", 30, "point", false],
  ["Daylight", 3, "evocation", 60, "point", false],
  ["Dispel Magic", 3, "abjuration", 120, "single", false],
  ["Elemental Weapon", 3, "transmutation", "touch", "single", true],
  ["Fear", 3, "illusion", "self", "area", true],
  ["Feign Death", 3, "necromancy", "touch", "single", false],
  ["Fireball", 3, "evocation", 150, "area", false],
  ["Fly", 3, "transmutation", "touch", "single", true],
  ["Gaseous Form", 3, "transmutation", "touch", "single", true],
  ["Glyph of Warding", 3, "abjuration", "touch", "point", false],
  ["Haste", 3, "transmutation", 30, "single", true],
  ["Hunger of Hadar", 3, "conjuration", 150, "area", true],
  ["Hypnotic Pattern", 3, "illusion", 120, "area", true],
  ["Lightning Bolt", 3, "evocation", "self", "area", false],
  ["Magic Circle", 3, "abjuration", 10, "point", false],
  ["Major Image", 3, "illusion", 120, "area", true],
  ["Mass Healing Word", 3, "evocation", 60, "area", false],
  ["Meld into Stone", 3, "transmutation", "touch", "self", false],
  ["Nondetection", 3, "abjuration", "touch", "single", false],
  ["Plant Growth", 3, "transmutation", 150, "area", false],
  ["Protection from Energy", 3, "abjuration", "touch", "single", true],
  ["Remove Curse", 3, "abjuration", "touch", "single", false],
  ["Revivify", 3, "necromancy", "touch", "single", false],
  ["Sending", 3, "divination", 5000, "single", false],
  ["Sleet Storm", 3, "conjuration", 150, "area", true],
  ["Slow", 3, "transmutation", 120, "area", true],
  ["Speak with Dead", 3, "necromancy", 10, "single", false],
  ["Speak with Plants", 3, "transmutation", "self", "area", false],
  ["Spirit Guardians", 3, "conjuration", "self", "area", true],
  ["Stinking Cloud", 3, "conjuration", 90, "area", true],
  ["Tongues", 3, "divination", "touch", "single", false],
  ["Vampiric Touch", 3, "necromancy", "self", "single", true],
  ["Water Breathing", 3, "transmutation", 30, "area", false],
  ["Water Walk", 3, "transmutation", 30, "area", false],
  ["Wind Wall", 3, "evocation", 120, "area", true],

  // Level 4
  ["Arcane Eye", 4, "divination", 30, "point", true],
  ["Aura of Life", 4, "abjuration", "self", "area", true],
  ["Aura of Purity", 4, "abjuration", "self", "area", true],
  ["Banishment", 4, "abjuration", 60, "single", true],
  ["Blight", 4, "necromancy", 30, "single", false],
  ["Compulsion", 4, "enchantment", 30, "single", true],
  ["Confusion", 4, "enchantment", 90, "area", true],
  ["Conjure Minor Elementals", 4, "conjuration", 90, "area", true],
  ["Conjure Woodland Beings", 4, "conjuration", 60, "area", true],
  ["Control Water", 4, "transmutation", 300, "area", true],
  ["Death Ward", 4, "abjuration", "touch", "single", false],
  ["Dimension Door", 4, "conjuration", 500, "self", false],
  ["Divination", 4, "divination", "self", "self", false],
  ["Dominate Beast", 4, "enchantment", 60, "single", true],
  ["Fabricate", 4, "transmutation", 120, "point", false],
  ["Faithful Hound", 4, "conjuration", 30, "point", false],
  ["Fire Shield", 4, "evocation", "self", "self", false],
  ["Freedom of Movement", 4, "abjuration", "touch", "single", false],
  ["Giant Insect", 4, "transmutation", 30, "area", true],
  ["Grasping Vine", 4, "conjuration", 30, "point", true],
  ["Greater Invisibility", 4, "illusion", "touch", "single", true],
  ["Guardian of Faith", 4, "conjuration", 30, "point", false],
  ["Hallucinatory Terrain", 4, "illusion", 300, "area", false],
  ["Ice Storm", 4, "evocation", 300, "area", false],
  ["Locate Creature", 4, "divination", "self", "self", true],
  ["Private Sanctum", 4, "abjuration", 120, "point", false],
  ["Resilient Sphere", 4, "evocation", 30, "single", true],
  ["Phantasmal Killer", 4, "illusion", 120, "single", true],
  ["Polymorph", 4, "transmutation", 60, "single", true],
  ["Stone Shape", 4, "transmutation", "touch", "point", false],
  ["Stoneskin", 4, "abjuration", "touch", "single", true],
  ["Wall of Fire", 4, "evocation", 120, "area", true],

  // Level 5
  ["Animate Objects", 5, "transmutation", 120, "area", true],
  ["Antilife Shell", 5, "abjuration", "self", "self", true],
  ["Awaken", 5, "transmutation", "touch", "single", false],
  ["Banishing Smite", 5, "abjuration", "self", "self", true],
  ["Arcane Hand", 5, "evocation", 120, "point", true],
  ["Circle of Power", 5, "abjuration", "self", "area", true],
  ["Cloudkill", 5, "conjuration", 120, "area", true],
  ["Commune", 5, "divination", "self", "self", false],
  ["Commune with Nature", 5, "divination", "self", "self", false],
  ["Cone of Cold", 5, "evocation", "self", "area", false],
  ["Conjure Elemental", 5, "conjuration", 90, "area", true],
  ["Contact Other Plane", 5, "divination", "self", "self", false],
  ["Contagion", 5, "necromancy", "touch", "single", false],
  ["Creation", 5, "illusion", 30, "point", false],
  ["Destructive Wave", 5, "evocation", "self", "area", false],
  ["Dispel Evil and Good", 5, "abjuration", "self", "self", true],
  ["Dominate Person", 5, "enchantment", 60, "single", true],
  ["Dream", 5, "illusion", 5000, "single", true],
  ["Flame Strike", 5, "evocation", 60, "area", false],
  ["Geas", 5, "enchantment", 60, "single", false],
  ["Greater Restoration", 5, "abjuration", "touch", "single", false],
  ["Hallow", 5, "evocation", "touch", "point", false],
  ["Hold Monster", 5, "enchantment", 90, "single", true],
  ["Insect Plague", 5, "conjuration", 300, "area", true],
  ["Legend Lore", 5, "divination", "self", "self", false],
  ["Mass Cure Wounds", 5, "evocation", 60, "area", false],
  ["Modify Memory", 5, "enchantment", 30, "single", true],
  ["Passwall", 5, "transmutation", "touch", "point", false],
  ["Planar Binding", 5, "abjuration", 60, "single", false],
  ["Raise Dead", 5, "necromancy", "touch", "single", false],
  ["Telepathic Bond", 5, "divination", 30, "area", false],
  ["Reincarnate", 5, "transmutation", "touch", "single", false],
  ["Scrying", 5, "divination", "self", "single", true],
  ["Seeming", 5, "illusion", 30, "area", false],
  ["Swift Quiver", 5, "transmutation", 60, "single", true],
  ["Telekinesis", 5, "transmutation", 60, "single", true],
  ["Teleportation Circle", 5, "conjuration", 10, "point", false],
  ["Tree Stride", 5, "transmutation", "self", "self", true],
  ["Wall of Force", 5, "evocation", 120, "area", true],
  ["Wall of Stone", 5, "evocation", 120, "area", true],

  // Level 6
  ["Arcane Gate", 6, "conjuration", 500, "point", true],
  ["Blade Barrier", 6, "evocation", 90, "area", true],
  ["Chain Lightning", 6, "evocation", 150, "area", false],
  ["Circle of Death", 6, "necromancy", 150, "area", false],
  ["Conjure Fey", 6, "conjuration", 90, "area", true],
  ["Contingency", 6, "transmutation", "self", "self", false],
  ["Create Undead", 6, "necromancy", 10, "point", false],
  ["Disintegrate", 6, "transmutation", 60, "single", false],
  ["Instant Summons", 6, "conjuration", "touch", "point", false],
  ["Eyebite", 6, "necromancy", "self", "single", true],
  ["Find the Path", 6, "divination", "self", "self", true],
  ["Flesh to Stone", 6, "transmutation", 60, "single", true],
  ["Forbiddance", 6, "abjuration", "touch", "area", false],
  ["Globe of Invulnerability", 6, "abjuration", "self", "self", true],
  ["Guards and Wards", 6, "abjuration", "touch", "point", false],
  ["Harm", 6, "necromancy", 60, "single", false],
  ["Heal", 6, "evocation", 60, "single", false],
  ["Heroes' Feast", 6, "conjuration", 30, "point", false],
  ["Magic Jar", 6, "necromancy", "self", "single", false],
  ["Mass Suggestion", 6, "enchantment", 60, "single", false],
  ["Move Earth", 6, "transmutation", 120, "area", true],
  ["Freezing Sphere", 6, "evocation", 300, "area", false],
  ["Irresistible Dance", 6, "enchantment", 30, "single", true],
  ["Planar Ally", 6, "conjuration", 60, "single", false],
  ["Programmed Illusion", 6, "illusion", 120, "point", false],
  ["Sunbeam", 6, "evocation", "self", "area", true],
  ["Transport via Plants", 6, "conjuration", 10, "point", false],
  ["True Seeing", 6, "divination", "touch", "single", false],
  ["Wall of Ice", 6, "evocation", 120, "area", true],
  ["Wind Walk", 6, "transmutation", 30, "area", false],
  ["Word of Recall", 6, "conjuration", "touch", "self", false],

  // Level 7
  ["Conjure Celestial", 7, "conjuration", 90, "area", true],
  ["Delayed Blast Fireball", 7, "evocation", 150, "area", true],
  ["Divine Word", 7, "evocation", 30, "area", false],
  ["Etherealness", 7, "transmutation", "self", "self", false],
  ["Finger of Death", 7, "necromancy", 60, "single", false],
  ["Fire Storm", 7, "evocation", 150, "area", false],
  ["Forcecage", 7, "evocation", 100, "area", false],
  ["Mirage Arcane", 7, "illusion", "self", "area", false],
  ["Magnificent Mansion", 7, "conjuration", 300, "point", false],
  ["Arcane Sword", 7, "evocation", 60, "single", true],
  ["Plane Shift", 7, "conjuration", "touch", "single", false],
  ["Prismatic Spray", 7, "evocation", "self", "area", false],
  ["Project Image", 7, "illusion", 500, "single", true],
  ["Regenerate", 7, "transmutation", "touch", "single", false],
  ["Resurrection", 7, "necromancy", "touch", "single", false],
  ["Reverse Gravity", 7, "transmutation", 50, "area", true],
  ["Sequester", 7, "transmutation", "touch", "single", false],
  ["Simulacrum", 7, "illusion", "touch", "point", false],
  ["Symbol", 7, "abjuration", "touch", "point", false],
  ["Teleport", 7, "conjuration", 10, "point", false],

  // Level 8
  ["Animal Shapes", 8, "transmutation", 30, "area", false],
  ["Antimagic Field", 8, "abjuration", "self", "self", true],
  ["Antipathy/Sympathy", 8, "enchantment", 60, "point", false],
  ["Clone", 8, "necromancy", "touch", "single", false],
  ["Control Weather", 8, "transmutation", "self", "self", true],
  ["Demiplane", 8, "conjuration", 60, "point", false],
  ["Dominate Monster", 8, "enchantment", 60, "single", true],
  ["Earthquake", 8, "evocation", 500, "area", true],
  ["Feeblemind", 8, "enchantment", 150, "single", false],
  ["Glibness", 8, "enchantment", "self", "self", false],
  ["Holy Aura", 8, "abjuration", "self", "area", true],
  ["Incendiary Cloud", 8, "conjuration", 150, "area", true],
  ["Maze", 8, "conjuration", 60, "single", true],
  ["Mind Blank", 8, "abjuration", "touch", "single", false],
  ["Power Word Stun", 8, "enchantment", 60, "single", false],
  ["Sunburst", 8, "evocation", 150, "area", false],
  ["Telepathy", 8, "evocation", 5000, "single", false],
  ["Tsunami", 8, "conjuration", 500, "area", true],

  // Level 9
  ["Astral Projection", 9, "necromancy", "touch", "self", false],
  ["Foresight", 9, "divination", "touch", "single", false],
  ["Gate", 9, "conjuration", 60, "point", true],
  ["Imprisonment", 9, "abjuration", "touch", "single", false],
  ["Mass Heal", 9, "evocation", 60, "area", false],
  ["Meteor Swarm", 9, "evocation", 1000, "area", false],
  ["Power Word Kill", 9, "enchantment", 60, "single", false],
  ["Prismatic Wall", 9, "abjuration", 60, "area", false],
  ["Shapechange", 9, "transmutation", "self", "self", true],
  ["Storm of Vengeance", 9, "conjuration", 500, "area", true],
  ["Time Stop", 9, "transmutation", "self", "self", false],
  ["True Polymorph", 9, "transmutation", 30, "single", true],
  ["True Resurrection", 9, "necromancy", "touch", "single", false],
  ["Weird", 9, "illusion", 120, "area", true],
  ["Wish", 9, "conjuration", "self", "self", false],
];

/**
 * Spell-attack metadata (Prompt 51), cross-checked against the actual SRD
 * 5.1 spell descriptions the same way Prompt 47's condition catalog was —
 * an entry exists ONLY where the SRD text says "make a melee spell attack"
 * or "make a ranged spell attack" AND the spell deals fixed on-hit damage
 * dice. `damageNotation` is the BASE dice (cantrips at character level 1-4;
 * cantrip level scaling isn't modeled anywhere in the app — the manual
 * attack flow types damage by hand too); per-hit riders (Acid Arrow's
 * end-of-turn 2d4, Witch Bolt's sustained arc) and multi-beam repetition
 * (Scorching Ray's three rays are three separate attack rolls at 2d6 each)
 * stay narration, exactly like the manual flow.
 *
 * Deliberately ABSENT despite the SRD using a spell attack roll:
 * - Produce Flame, Flame Blade, Vampiric Touch — catalog `range: "self"`
 *   (the attack happens from a self-range effect), and self-range spells
 *   are excluded from the quick-actions surface by design.
 * - Ray of Enfeeblement, Contagion — a spell attack roll but NO damage
 *   dice; the attack flow requires damage notation.
 * - Spiritual Weapon, Arcane Hand, Arcane Sword — conjured effects whose
 *   attacks recur on later bonus actions (and Spiritual Weapon adds the
 *   caster's ability modifier to damage, which a static notation can't
 *   express); not a single cast-and-resolve attack.
 * Saving-throw spells (Acid Splash, Sacred Flame, Poison Spray, Fireball…)
 * and auto-hit spells (Magic Missile) are out of scope per the Spell.attack
 * contract.
 */
const SPELL_ATTACKS: Record<string, SpellAttack> = {
  // Cantrips
  "Chill Touch": { kind: "ranged", damageNotation: "1d8" }, // ranged despite the name — SRD: "make a ranged spell attack", 1d8 necrotic
  "Eldritch Blast": { kind: "ranged", damageNotation: "1d10" }, // 1d10 force per beam
  "Fire Bolt": { kind: "ranged", damageNotation: "1d10" }, // 1d10 fire
  "Ray of Frost": { kind: "ranged", damageNotation: "1d8" }, // 1d8 cold
  "Shocking Grasp": { kind: "melee", damageNotation: "1d8" }, // 1d8 lightning
  // Level 1
  "Chromatic Orb": { kind: "ranged", damageNotation: "3d8" }, // 3d8 of the chosen type
  "Guiding Bolt": { kind: "ranged", damageNotation: "4d6" }, // 4d6 radiant
  "Inflict Wounds": { kind: "melee", damageNotation: "3d10" }, // 3d10 necrotic
  "Ray of Sickness": { kind: "ranged", damageNotation: "2d8" }, // 2d8 poison
  "Witch Bolt": { kind: "ranged", damageNotation: "1d12" }, // 1d12 lightning on the initial attack
  // Level 2
  "Acid Arrow": { kind: "ranged", damageNotation: "4d4" }, // 4d4 acid on hit (the delayed 2d4 is a rider)
  "Scorching Ray": { kind: "ranged", damageNotation: "2d6" }, // 2d6 fire per ray
};

/**
 * Class spell lists (Prompt 52), cross-checked against SRD 5.1 / PHB
 * Appendix PH-A "Spell Lists" (Bard/Cleric/Druid/Sorcerer/Warlock/Wizard)
 * and the Paladin/Ranger spell tables embedded in those classes'
 * descriptions. Barbarian, Fighter, Monk, and Rogue are non-casters and
 * always resolve to an empty list here — their SRD-legal subclasses in
 * this app's catalog grant no spellcasting (Eldritch Knight/Arcane
 * Trickster aren't modeled), so they never appear in any spell's
 * `classes` array.
 *
 * Half-casters (Paladin, Ranger) are listed only through the 5th-level
 * spells the SRD actually grants them — they never get 6th-9th level
 * spells regardless of character level, so those levels are simply
 * absent from their entries. Warlock is listed all the way through 9th
 * level: Pact Magic slots cap at 5th, but the Mystic Arcanum feature lets
 * a Warlock cast one 6th-9th level spell each from the Warlock spell
 * list itself, so the SRD's Warlock list — and this catalog's — extends
 * the full 9 levels.
 */
const CLASS_SPELL_LISTS: Record<ClassName, string[]> = {
  Barbarian: [],
  Bard: [
    // Cantrips
    "Blade Ward",
    "Dancing Lights",
    "Friends",
    "Light",
    "Mage Hand",
    "Mending",
    "Message",
    "Minor Illusion",
    "Prestidigitation",
    "True Strike",
    "Vicious Mockery",
    // 1st
    "Animal Friendship",
    "Bane",
    "Charm Person",
    "Comprehend Languages",
    "Cure Wounds",
    "Detect Magic",
    "Disguise Self",
    "Dissonant Whispers",
    "Faerie Fire",
    "Feather Fall",
    "Healing Word",
    "Heroism",
    "Hideous Laughter",
    "Identify",
    "Illusory Script",
    "Longstrider",
    "Silent Image",
    "Sleep",
    "Speak with Animals",
    "Thunderwave",
    "Unseen Servant",
    // 2nd
    "Animal Messenger",
    "Blindness/Deafness",
    "Crown of Madness",
    "Detect Thoughts",
    "Enhance Ability",
    "Enthrall",
    "Heat Metal",
    "Hold Person",
    "Invisibility",
    "Knock",
    "Lesser Restoration",
    "Locate Animals or Plants",
    "Locate Object",
    "Magic Mouth",
    "See Invisibility",
    "Shatter",
    "Silence",
    "Suggestion",
    "Zone of Truth",
    // 3rd
    "Bestow Curse",
    "Clairvoyance",
    "Dispel Magic",
    "Fear",
    "Feign Death",
    "Glyph of Warding",
    "Hypnotic Pattern",
    "Major Image",
    "Nondetection",
    "Plant Growth",
    "Sending",
    "Speak with Dead",
    "Speak with Plants",
    "Stinking Cloud",
    "Tongues",
    // 4th
    "Compulsion",
    "Confusion",
    "Dimension Door",
    "Freedom of Movement",
    "Greater Invisibility",
    "Hallucinatory Terrain",
    "Locate Creature",
    "Polymorph",
    // 5th
    "Animate Objects",
    "Awaken",
    "Dominate Person",
    "Dream",
    "Geas",
    "Greater Restoration",
    "Hold Monster",
    "Legend Lore",
    "Mass Cure Wounds",
    "Modify Memory",
    "Planar Binding",
    "Raise Dead",
    "Scrying",
    "Seeming",
    "Teleportation Circle",
    // 6th
    "Eyebite",
    "Find the Path",
    "Guards and Wards",
    "Irresistible Dance",
    "Mass Suggestion",
    "Programmed Illusion",
    "True Seeing",
    // 7th
    "Arcane Sword",
    "Etherealness",
    "Forcecage",
    "Magnificent Mansion",
    "Mirage Arcane",
    "Project Image",
    "Regenerate",
    "Resurrection",
    "Symbol",
    "Teleport",
    // 8th
    "Dominate Monster",
    "Feeblemind",
    "Glibness",
    "Mind Blank",
    "Power Word Stun",
    // 9th
    "Foresight",
    "Power Word Kill",
    "True Polymorph",
  ],
  Cleric: [
    // Cantrips
    "Guidance",
    "Light",
    "Mending",
    "Resistance",
    "Sacred Flame",
    "Spare the Dying",
    "Thaumaturgy",
    // 1st
    "Bane",
    "Bless",
    "Command",
    "Create or Destroy Water",
    "Cure Wounds",
    "Detect Evil and Good",
    "Detect Magic",
    "Detect Poison and Disease",
    "Guiding Bolt",
    "Healing Word",
    "Inflict Wounds",
    "Protection from Evil and Good",
    "Purify Food and Drink",
    "Sanctuary",
    "Shield of Faith",
    // 2nd
    "Aid",
    "Augury",
    "Blindness/Deafness",
    "Continual Flame",
    "Enhance Ability",
    "Find Traps",
    "Gentle Repose",
    "Hold Person",
    "Lesser Restoration",
    "Locate Object",
    "Prayer of Healing",
    "Protection from Poison",
    "Silence",
    "Spiritual Weapon",
    "Warding Bond",
    "Zone of Truth",
    // 3rd
    "Animate Dead",
    "Bestow Curse",
    "Clairvoyance",
    "Create Food and Water",
    "Daylight",
    "Dispel Magic",
    "Glyph of Warding",
    "Magic Circle",
    "Mass Healing Word",
    "Meld into Stone",
    "Remove Curse",
    "Revivify",
    "Sending",
    "Speak with Dead",
    "Spirit Guardians",
    "Tongues",
    "Water Walk",
    // 4th
    "Banishment",
    "Control Water",
    "Death Ward",
    "Divination",
    "Freedom of Movement",
    "Guardian of Faith",
    "Locate Creature",
    "Stone Shape",
    // 5th
    "Commune",
    "Contagion",
    "Dispel Evil and Good",
    "Flame Strike",
    "Geas",
    "Greater Restoration",
    "Hallow",
    "Insect Plague",
    "Legend Lore",
    "Mass Cure Wounds",
    "Planar Binding",
    "Raise Dead",
    "Scrying",
    // 6th
    "Blade Barrier",
    "Create Undead",
    "Find the Path",
    "Forbiddance",
    "Harm",
    "Heal",
    "Heroes' Feast",
    "Planar Ally",
    "True Seeing",
    "Word of Recall",
    // 7th
    "Conjure Celestial",
    "Divine Word",
    "Etherealness",
    "Fire Storm",
    "Plane Shift",
    "Regenerate",
    "Resurrection",
    "Symbol",
    // 8th
    "Antimagic Field",
    "Control Weather",
    "Earthquake",
    "Holy Aura",
    // 9th
    "Astral Projection",
    "Gate",
    "Mass Heal",
    "True Resurrection",
  ],
  Druid: [
    // Cantrips
    "Druidcraft",
    "Guidance",
    "Mending",
    "Poison Spray",
    "Produce Flame",
    "Resistance",
    "Shillelagh",
    // 1st
    "Animal Friendship",
    "Charm Person",
    "Create or Destroy Water",
    "Cure Wounds",
    "Detect Magic",
    "Detect Poison and Disease",
    "Entangle",
    "Faerie Fire",
    "Fog Cloud",
    "Goodberry",
    "Healing Word",
    "Jump",
    "Longstrider",
    "Purify Food and Drink",
    "Speak with Animals",
    "Thunderwave",
    // 2nd
    "Animal Messenger",
    "Barkskin",
    "Beast Sense",
    "Darkvision",
    "Enhance Ability",
    "Find Traps",
    "Flame Blade",
    "Flaming Sphere",
    "Gust of Wind",
    "Heat Metal",
    "Hold Person",
    "Lesser Restoration",
    "Locate Animals or Plants",
    "Locate Object",
    "Moonbeam",
    "Pass without Trace",
    "Protection from Poison",
    "Spike Growth",
    // 3rd
    "Call Lightning",
    "Conjure Animals",
    "Daylight",
    "Dispel Magic",
    "Meld into Stone",
    "Plant Growth",
    "Protection from Energy",
    "Sleet Storm",
    "Speak with Plants",
    "Water Breathing",
    "Water Walk",
    "Wind Wall",
    // 4th
    "Blight",
    "Confusion",
    "Conjure Minor Elementals",
    "Conjure Woodland Beings",
    "Control Water",
    "Dominate Beast",
    "Freedom of Movement",
    "Giant Insect",
    "Grasping Vine",
    "Hallucinatory Terrain",
    "Ice Storm",
    "Locate Creature",
    "Polymorph",
    "Stone Shape",
    "Stoneskin",
    "Wall of Fire",
    // 5th
    "Antilife Shell",
    "Awaken",
    "Commune with Nature",
    "Conjure Elemental",
    "Contagion",
    "Geas",
    "Greater Restoration",
    "Insect Plague",
    "Mass Cure Wounds",
    "Planar Binding",
    "Reincarnate",
    "Scrying",
    "Tree Stride",
    "Wall of Stone",
    // 6th
    "Conjure Fey",
    "Find the Path",
    "Heal",
    "Heroes' Feast",
    "Move Earth",
    "Sunbeam",
    "Transport via Plants",
    "Wind Walk",
    // 7th
    "Fire Storm",
    "Mirage Arcane",
    "Plane Shift",
    "Regenerate",
    "Reverse Gravity",
    // 8th
    "Animal Shapes",
    "Antipathy/Sympathy",
    "Control Weather",
    "Earthquake",
    "Feeblemind",
    "Sunburst",
    "Tsunami",
    // 9th
    "Foresight",
    "Shapechange",
    "Storm of Vengeance",
    "True Resurrection",
  ],
  Fighter: [],
  Monk: [],
  Paladin: [
    // 1st
    "Bless",
    "Command",
    "Compelled Duel",
    "Cure Wounds",
    "Detect Evil and Good",
    "Detect Magic",
    "Detect Poison and Disease",
    "Divine Favor",
    "Heroism",
    "Protection from Evil and Good",
    "Purify Food and Drink",
    "Searing Smite",
    "Shield of Faith",
    "Thunderous Smite",
    "Wrathful Smite",
    // 2nd
    "Aid",
    "Branding Smite",
    "Find Steed",
    "Lesser Restoration",
    "Locate Object",
    "Magic Weapon",
    "Protection from Poison",
    "Zone of Truth",
    // 3rd
    "Create Food and Water",
    "Daylight",
    "Dispel Magic",
    "Elemental Weapon",
    "Magic Circle",
    "Remove Curse",
    "Revivify",
    // 4th
    "Aura of Life",
    "Aura of Purity",
    "Banishment",
    "Death Ward",
    "Locate Creature",
    // 5th
    "Banishing Smite",
    "Circle of Power",
    "Destructive Wave",
    "Dispel Evil and Good",
    "Geas",
    "Raise Dead",
  ],
  Ranger: [
    // 1st
    "Alarm",
    "Animal Friendship",
    "Cure Wounds",
    "Detect Magic",
    "Detect Poison and Disease",
    "Ensnaring Strike",
    "Fog Cloud",
    "Goodberry",
    "Hunter's Mark",
    "Jump",
    "Longstrider",
    "Speak with Animals",
    // 2nd
    "Animal Messenger",
    "Barkskin",
    "Beast Sense",
    "Darkvision",
    "Find Traps",
    "Lesser Restoration",
    "Locate Animals or Plants",
    "Locate Object",
    "Pass without Trace",
    "Protection from Poison",
    "Silence",
    "Spike Growth",
    // 3rd
    "Conjure Animals",
    "Daylight",
    "Nondetection",
    "Plant Growth",
    "Protection from Energy",
    "Speak with Plants",
    "Water Breathing",
    "Water Walk",
    "Wind Wall",
    // 4th
    "Conjure Woodland Beings",
    "Freedom of Movement",
    "Grasping Vine",
    "Locate Creature",
    "Stoneskin",
    // 5th
    "Commune with Nature",
    "Swift Quiver",
    "Tree Stride",
  ],
  Rogue: [],
  Sorcerer: [
    // Cantrips
    "Acid Splash",
    "Blade Ward",
    "Chill Touch",
    "Dancing Lights",
    "Fire Bolt",
    "Friends",
    "Light",
    "Mage Hand",
    "Mending",
    "Message",
    "Minor Illusion",
    "Poison Spray",
    "Prestidigitation",
    "Ray of Frost",
    "Shocking Grasp",
    "True Strike",
    // 1st
    "Burning Hands",
    "Charm Person",
    "Chromatic Orb",
    "Color Spray",
    "Comprehend Languages",
    "Detect Magic",
    "Disguise Self",
    "Expeditious Retreat",
    "False Life",
    "Feather Fall",
    "Fog Cloud",
    "Jump",
    "Mage Armor",
    "Magic Missile",
    "Ray of Sickness",
    "Shield",
    "Silent Image",
    "Sleep",
    "Thunderwave",
    "Witch Bolt",
    // 2nd
    "Alter Self",
    "Blindness/Deafness",
    "Blur",
    "Crown of Madness",
    "Darkness",
    "Darkvision",
    "Detect Thoughts",
    "Enhance Ability",
    "Enlarge/Reduce",
    "Gust of Wind",
    "Hold Person",
    "Invisibility",
    "Knock",
    "Levitate",
    "Mirror Image",
    "Misty Step",
    "Scorching Ray",
    "See Invisibility",
    "Shatter",
    "Spider Climb",
    "Suggestion",
    "Web",
    // 3rd
    "Blink",
    "Clairvoyance",
    "Counterspell",
    "Daylight",
    "Dispel Magic",
    "Fear",
    "Fireball",
    "Fly",
    "Gaseous Form",
    "Haste",
    "Hypnotic Pattern",
    "Lightning Bolt",
    "Major Image",
    "Protection from Energy",
    "Sleet Storm",
    "Slow",
    "Stinking Cloud",
    "Tongues",
    "Water Breathing",
    "Water Walk",
    // 4th
    "Banishment",
    "Blight",
    "Confusion",
    "Dimension Door",
    "Dominate Beast",
    "Greater Invisibility",
    "Ice Storm",
    "Polymorph",
    "Stoneskin",
    "Wall of Fire",
    // 5th
    "Animate Objects",
    "Cloudkill",
    "Cone of Cold",
    "Creation",
    "Dominate Person",
    "Hold Monster",
    "Insect Plague",
    "Seeming",
    "Telekinesis",
    "Teleportation Circle",
    "Wall of Stone",
    // 6th
    "Chain Lightning",
    "Circle of Death",
    "Disintegrate",
    "Eyebite",
    "Globe of Invulnerability",
    "Mass Suggestion",
    "Move Earth",
    "Sunbeam",
    "True Seeing",
    // 7th
    "Delayed Blast Fireball",
    "Etherealness",
    "Finger of Death",
    "Fire Storm",
    "Plane Shift",
    "Prismatic Spray",
    "Reverse Gravity",
    "Teleport",
    // 8th
    "Dominate Monster",
    "Earthquake",
    "Incendiary Cloud",
    "Power Word Stun",
    "Sunburst",
    // 9th
    "Gate",
    "Meteor Swarm",
    "Power Word Kill",
    "Time Stop",
    "Wish",
  ],
  Warlock: [
    // Cantrips
    "Blade Ward",
    "Chill Touch",
    "Eldritch Blast",
    "Friends",
    "Mage Hand",
    "Minor Illusion",
    "Poison Spray",
    "Prestidigitation",
    "True Strike",
    // 1st
    "Charm Person",
    "Comprehend Languages",
    "Expeditious Retreat",
    "Hex",
    "Illusory Script",
    "Protection from Evil and Good",
    "Unseen Servant",
    "Witch Bolt",
    // 2nd
    "Crown of Madness",
    "Darkness",
    "Enthrall",
    "Hold Person",
    "Invisibility",
    "Mirror Image",
    "Misty Step",
    "Ray of Enfeeblement",
    "Shatter",
    "Spider Climb",
    "Suggestion",
    // 3rd
    "Counterspell",
    "Dispel Magic",
    "Fear",
    "Fly",
    "Gaseous Form",
    "Hunger of Hadar",
    "Hypnotic Pattern",
    "Magic Circle",
    "Major Image",
    "Remove Curse",
    "Tongues",
    "Vampiric Touch",
    // 4th
    "Banishment",
    "Blight",
    "Dimension Door",
    "Hallucinatory Terrain",
    // 5th
    "Contact Other Plane",
    "Dream",
    "Hold Monster",
    "Scrying",
    // 6th (Mystic Arcanum)
    "Circle of Death",
    "Conjure Fey",
    "Create Undead",
    "Eyebite",
    "Flesh to Stone",
    "Mass Suggestion",
    "True Seeing",
    // 7th (Mystic Arcanum)
    "Etherealness",
    "Finger of Death",
    "Forcecage",
    "Plane Shift",
    // 8th (Mystic Arcanum)
    "Demiplane",
    "Dominate Monster",
    "Feeblemind",
    "Glibness",
    "Power Word Stun",
    // 9th (Mystic Arcanum)
    "Astral Projection",
    "Foresight",
    "Imprisonment",
    "Power Word Kill",
    "True Polymorph",
  ],
  Wizard: [
    // Cantrips
    "Acid Splash",
    "Blade Ward",
    "Chill Touch",
    "Dancing Lights",
    "Fire Bolt",
    "Friends",
    "Light",
    "Mage Hand",
    "Mending",
    "Message",
    "Minor Illusion",
    "Poison Spray",
    "Prestidigitation",
    "Ray of Frost",
    "Shocking Grasp",
    "True Strike",
    // 1st
    "Alarm",
    "Burning Hands",
    "Charm Person",
    "Chromatic Orb",
    "Color Spray",
    "Comprehend Languages",
    "Detect Magic",
    "Disguise Self",
    "Expeditious Retreat",
    "False Life",
    "Feather Fall",
    "Find Familiar",
    "Floating Disk",
    "Fog Cloud",
    "Grease",
    "Hideous Laughter",
    "Identify",
    "Illusory Script",
    "Jump",
    "Longstrider",
    "Mage Armor",
    "Magic Missile",
    "Protection from Evil and Good",
    "Ray of Sickness",
    "Shield",
    "Silent Image",
    "Sleep",
    "Thunderwave",
    "Unseen Servant",
    "Witch Bolt",
    // 2nd
    "Acid Arrow",
    "Alter Self",
    "Arcane Lock",
    "Blindness/Deafness",
    "Blur",
    "Continual Flame",
    "Crown of Madness",
    "Darkness",
    "Darkvision",
    "Detect Thoughts",
    "Enlarge/Reduce",
    "Flaming Sphere",
    "Gentle Repose",
    "Gust of Wind",
    "Hold Person",
    "Invisibility",
    "Knock",
    "Levitate",
    "Locate Object",
    "Magic Mouth",
    "Magic Weapon",
    "Mirror Image",
    "Misty Step",
    "Ray of Enfeeblement",
    "Rope Trick",
    "Scorching Ray",
    "See Invisibility",
    "Shatter",
    "Spider Climb",
    "Suggestion",
    "Web",
    // 3rd
    "Animate Dead",
    "Bestow Curse",
    "Blink",
    "Clairvoyance",
    "Counterspell",
    "Dispel Magic",
    "Fear",
    "Feign Death",
    "Fireball",
    "Fly",
    "Gaseous Form",
    "Glyph of Warding",
    "Haste",
    "Hypnotic Pattern",
    "Lightning Bolt",
    "Magic Circle",
    "Major Image",
    "Nondetection",
    "Protection from Energy",
    "Remove Curse",
    "Sending",
    "Sleet Storm",
    "Slow",
    "Stinking Cloud",
    "Tongues",
    "Vampiric Touch",
    "Water Breathing",
    // 4th
    "Arcane Eye",
    "Banishment",
    "Blight",
    "Confusion",
    "Conjure Minor Elementals",
    "Control Water",
    "Dimension Door",
    "Divination",
    "Fabricate",
    "Faithful Hound",
    "Fire Shield",
    "Greater Invisibility",
    "Hallucinatory Terrain",
    "Ice Storm",
    "Locate Creature",
    "Phantasmal Killer",
    "Polymorph",
    "Private Sanctum",
    "Resilient Sphere",
    "Stone Shape",
    "Stoneskin",
    "Wall of Fire",
    // 5th
    "Animate Objects",
    "Arcane Hand",
    "Cloudkill",
    "Cone of Cold",
    "Conjure Elemental",
    "Contact Other Plane",
    "Creation",
    "Dominate Person",
    "Dream",
    "Geas",
    "Hold Monster",
    "Legend Lore",
    "Modify Memory",
    "Passwall",
    "Planar Binding",
    "Scrying",
    "Seeming",
    "Telekinesis",
    "Telepathic Bond",
    "Teleportation Circle",
    "Wall of Force",
    "Wall of Stone",
    // 6th
    "Arcane Gate",
    "Chain Lightning",
    "Circle of Death",
    "Contingency",
    "Create Undead",
    "Disintegrate",
    "Eyebite",
    "Flesh to Stone",
    "Freezing Sphere",
    "Globe of Invulnerability",
    "Guards and Wards",
    "Instant Summons",
    "Irresistible Dance",
    "Magic Jar",
    "Mass Suggestion",
    "Move Earth",
    "Programmed Illusion",
    "Sunbeam",
    "True Seeing",
    "Wall of Ice",
    // 7th
    "Arcane Sword",
    "Delayed Blast Fireball",
    "Etherealness",
    "Finger of Death",
    "Forcecage",
    "Magnificent Mansion",
    "Mirage Arcane",
    "Plane Shift",
    "Prismatic Spray",
    "Project Image",
    "Reverse Gravity",
    "Sequester",
    "Simulacrum",
    "Symbol",
    "Teleport",
    // 8th
    "Antimagic Field",
    "Antipathy/Sympathy",
    "Clone",
    "Control Weather",
    "Demiplane",
    "Dominate Monster",
    "Feeblemind",
    "Incendiary Cloud",
    "Maze",
    "Mind Blank",
    "Power Word Stun",
    "Sunburst",
    "Telepathy",
    // 9th
    "Astral Projection",
    "Foresight",
    "Gate",
    "Imprisonment",
    "Meteor Swarm",
    "Power Word Kill",
    "Prismatic Wall",
    "Shapechange",
    "Time Stop",
    "True Polymorph",
    "Weird",
    "Wish",
  ],
};

const SPELL_CLASSES: Record<string, ClassName[]> = (() => {
  const map: Record<string, ClassName[]> = {};
  for (const [className, spellNames] of Object.entries(CLASS_SPELL_LISTS) as [ClassName, string[]][]) {
    for (const name of spellNames) {
      (map[name] ??= []).push(className);
    }
  }
  return map;
})();

export const SPELLS: Spell[] = SPELL_TUPLES.map(([name, level, school, range, targetType, concentration]) => ({
  name,
  level,
  school,
  range,
  targetType,
  concentration,
  classes: SPELL_CLASSES[name] ?? [],
  ...(SPELL_ATTACKS[name] ? { attack: SPELL_ATTACKS[name] } : {}),
}));
