import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import { GlobalMusic } from "./GlobalMusic";
import "./globals.css";

// Backs --font-b (body copy) in tokens.css. A body font can safely go
// through next/font since nothing references its exact family name as a
// literal string (unlike --font-h, see the raw <link> below).
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// Backs --font-m (the monospace label/eyebrow convention used throughout
// the app) in tokens.css. Same reasoning as Inter above.
const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${inter.variable} ${jetbrainsMono.variable}`}>
      <body>
        {/*
          Display faces for the ported neon/CRT tokens: the locked token
          stacks reference the literal family names 'Share Tech' and
          'Orbitron' (see src/ui-components/tokens.css), so they must be
          loaded under those exact names — next/font registers hashed
          family names the verbatim stacks could never match.
        */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        {/* eslint-disable-next-line @next/next/no-page-custom-font --
            Pages-Router rule misfiring on the App Router root layout,
            which applies to every route (exactly what the rule asks for). */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400..700&family=Share+Tech&display=swap"
        />
        <GlobalMusic />
        {children}
      </body>
    </html>
  );
}
