-- Prompt 24: seed the built-in preset map assets. Generated by
-- scripts/assets/generate-map-presets.mjs — regenerate there, don't hand-edit.
--
-- Seeded via migration (as postgres, bypassing RLS) because 0015's insert
-- policy deliberately forbids preset rows (campaign_id null) through the
-- app path — presets are seeded data by design. Fixed UUIDs keep the rows'
-- identity stable and inspectable across environments.

insert into public.asset_library (id, name, source_type, model_ref) values
  ('a55e7001-0000-4000-8000-000000000001', 'Torch', 'preset', '/assets/presets/torch.glb'),
  ('a55e7002-0000-4000-8000-000000000002', 'Chest', 'preset', '/assets/presets/chest.glb'),
  ('a55e7003-0000-4000-8000-000000000003', 'Door', 'preset', '/assets/presets/door.glb'),
  ('a55e7004-0000-4000-8000-000000000004', 'Table', 'preset', '/assets/presets/table.glb'),
  ('a55e7005-0000-4000-8000-000000000005', 'Tree', 'preset', '/assets/presets/tree.glb'),
  ('a55e7006-0000-4000-8000-000000000006', 'Rock', 'preset', '/assets/presets/rock.glb'),
  ('a55e7007-0000-4000-8000-000000000007', 'Wall Segment', 'preset', '/assets/presets/wall.glb'),
  ('a55e7008-0000-4000-8000-000000000008', 'Stairs', 'preset', '/assets/presets/stairs.glb')
on conflict (id) do nothing;
