-- Procedural-wall gap/corner/diagonal fix (a post-roadmap addition, not one
-- of the numbered prompts) — no schema changes needed (asset_library
-- already has everything a preset row needs), just two new built-in preset
-- rows for the two new wall variants generated by
-- scripts/assets/generate-wall-variants-presets.mjs:
--   - "Wall Corner" (wall-corner.glb): a proper 90°-turn piece, used at any
--     cell where a wall run turns a real right angle — templates.ts's
--     classifyWallCell picks this over a plain "Wall Segment" the moment a
--     cell has wall neighbors on both a vertical AND a horizontal side.
--   - "Wall Diagonal" (wall-diagonal.glb): a 45°-orientation piece spanning
--     a single cell's own corner-to-corner diagonal, for octagonal/organic
--     room shapes (or the void-terrain-carved organic shapes this app
--     already supports) — manually placeable via the map editor's asset
--     palette like any other preset; nothing in templates.ts auto-selects it
--     today.
--
-- Seeded via migration as postgres, bypassing RLS, the identical
-- 0016_asset_library_presets.sql / 0053_crossing_structures.sql reasoning:
-- 0015's insert policy forbids preset rows (campaign_id null) through the
-- app path, so presets are seeded data by design. Fixed UUIDs one past
-- 0053's last (…009, Bridge) — keeps every built-in preset's identity in
-- one inspectable a55e7NNN numbering scheme across environments.
--
-- `on conflict do nothing` guards re-application the same way every prior
-- preset-seeding migration does, in case a dev stack already has these rows
-- from a direct, non-migration-tracked application under a different
-- filename (other concurrent agents may apply migrations directly to the
-- shared dev DB during testing).
insert into public.asset_library (id, name, source_type, model_ref) values
  ('a55e7010-0000-4000-8000-000000000010', 'Wall Corner', 'preset', '/assets/presets/wall-corner.glb'),
  ('a55e7011-0000-4000-8000-000000000011', 'Wall Diagonal', 'preset', '/assets/presets/wall-diagonal.glb')
on conflict (id) do nothing;
