-- Map Editor Batch A8a: medieval building exterior-facade presets — no
-- schema changes needed (asset_library already has everything a preset row
-- needs), just 8 new built-in preset rows for the buildings generated by
-- scripts/assets/generate-building-presets.mjs:
--   - "Cottage" (cottage.glb): a small stone house, thatched hip roof.
--   - "Timber House" (timber-house.glb): a Tudor-style plaster-and-exposed-
--     timber house, terracotta hip roof.
--   - "Roundhouse" (roundhouse.glb): a round wood-plank hut with a tall
--     conical thatch roof — a distinct silhouette from the two rectangular
--     houses above.
--   - "Town Hall" (town-hall.glb): a two-tier civic building with its own
--     corner clock/bell tower and entrance steps.
--   - "Tavern" (tavern.glb): a wide, jettied wooden building with a hanging
--     sign on an iron bracket.
--   - "Shop" (shop.glb): a plaster storefront with a display window and a
--     canvas awning.
--   - "Food Cart" (food-cart.glb): a small two-wheeled vendor's cart with a
--     canvas tent-canopy.
--   - "Farm Cart" (farm-cart.glb): a larger open two-wheeled cart with a
--     hay load and a forward yoke — no canopy, the clearest visual contrast
--     against the Food Cart.
--
-- Per this prompt's own Notes/Task: fewer distinct base models, leaning on
-- the separate object-coloring/tint feature (Map Editor Batch A3) for
-- visual variety rather than many fully bespoke models. Every preset here
-- is auto-normalized to fit a SINGLE cell at render time (PlacedObject.tsx's
-- existing maxDim-based scaling, unchanged) — the same "model-village
-- scale" convention every other built-in preset (Chest, Tree, Table, ...)
-- already uses. No existing preset needed a real multi-cell footprint
-- (confirmed by reading every prior preset-seeding migration before adding
-- this one), so no new multi-cell placement mechanic was introduced for
-- these either — see generate-building-presets.mjs's own top comment for
-- the full reasoning. That single-cell scaling is also why none of these
-- can overlap/clip a neighbor in ordinary placement: they occupy exactly
-- the same footprint budget as any other single-cell preset.
--
-- Seeded via migration as postgres, bypassing RLS, the identical
-- 0016_asset_library_presets.sql / 0053_crossing_structures.sql /
-- 0055_wall_variants.sql / 0059_interaction_events.sql reasoning: 0015's
-- insert policy forbids preset rows (campaign_id null) through the app
-- path, so presets are seeded data by design. Fixed UUIDs continue the
-- SAME a55e7NNN sequence 0016 established, one past 0059's last (Pressure
-- Plate, …013) — keeps every built-in preset's identity in one inspectable
-- numbering scheme across environments.
--
-- `on conflict do nothing` guards re-application the same way every prior
-- preset-seeding migration does, in case a dev stack already has these rows
-- from a direct, non-migration-tracked application under a different
-- filename (other concurrent agents may apply migrations directly to the
-- shared dev DB during testing).
insert into public.asset_library (id, name, source_type, model_ref) values
  ('a55e7014-0000-4000-8000-000000000014', 'Cottage', 'preset', '/assets/presets/cottage.glb'),
  ('a55e7015-0000-4000-8000-000000000015', 'Timber House', 'preset', '/assets/presets/timber-house.glb'),
  ('a55e7016-0000-4000-8000-000000000016', 'Roundhouse', 'preset', '/assets/presets/roundhouse.glb'),
  ('a55e7017-0000-4000-8000-000000000017', 'Town Hall', 'preset', '/assets/presets/town-hall.glb'),
  ('a55e7018-0000-4000-8000-000000000018', 'Tavern', 'preset', '/assets/presets/tavern.glb'),
  ('a55e7019-0000-4000-8000-000000000019', 'Shop', 'preset', '/assets/presets/shop.glb'),
  ('a55e7020-0000-4000-8000-000000000020', 'Food Cart', 'preset', '/assets/presets/food-cart.glb'),
  ('a55e7021-0000-4000-8000-000000000021', 'Farm Cart', 'preset', '/assets/presets/farm-cart.glb')
on conflict (id) do nothing;
