-- Weather & Enemies C6: default distinct 3D appearance per monster_templates
-- row (0073), generated by scripts/assets/generate-monster-presets.mjs — the
-- exact generate-building-presets.mjs (0066) seeding pattern: presets are
-- seeded data by design (0015's asset_library insert policy forbids
-- campaign_id-null rows through the app path), so these 8 rows are inserted
-- here, as postgres, bypassing RLS. Fixed UUIDs continue the SAME a55e7NNN
-- sequence 0016 established, one past 0066's last building preset (Farm
-- Cart, ...021) — keeps every built-in preset's identity in one inspectable
-- numbering scheme across environments.
--
-- default_asset_id on monster_templates is DELIBERATELY a SEPARATE concept
-- from the plain-value stat copy createMonsterStatBlockFromTemplate performs
-- (0073's own header comment called this out explicitly, in advance, before
-- this migration existed): it is a LIVE pointer, read fresh at render time
-- by MapSurface.tsx via the campaign's own resolved asset list — if an admin
-- later changes a template's default_asset_id (e.g. to a nicer model), every
-- campaign already using that template picks up the new appearance
-- automatically. This is completely independent of, and does not affect,
-- the one-time HP/AC/attacks/etc. copy already sitting in any campaign's own
-- monster_stat_blocks rows.
--
-- monster_stat_blocks.template_id (added below) is the OTHER half of that
-- same live-pointer mechanism: a nullable back-reference set ONLY when a
-- campaign's stat block was created via createMonsterStatBlockFromTemplate
-- (the quick-add-from-library flow). A pre-existing, hand-authored
-- (freeform) stat block has no template_id at all (column default null),
-- so MapSurface's token-rendering lookup (stat block -> template_id ->
-- monster_templates.default_asset_id -> asset_library.model_ref) simply
-- never resolves for it, and it keeps rendering exactly as it always has:
-- the flat allegiance-colored disc. ON DELETE SET NULL (not CASCADE): if an
-- admin ever deletes a template outright, campaigns that already copied its
-- stats keep their own independent stat block, just with no live visual
-- link any more (falls back to the flat disc) — deleting a template must
-- never delete anyone's placed monsters.
alter table public.monster_templates
  add column if not exists default_asset_id uuid references public.asset_library (id) on delete set null;

alter table public.monster_stat_blocks
  add column if not exists template_id uuid references public.monster_templates (id) on delete set null;

-- Seed content: 8 low-poly, dependency-free generated models, one per
-- 0073 template, each a genuinely distinct silhouette/proportion/color (not
-- a re-tinted copy of one shape) — see the generator script's own header
-- comment for the per-creature design reasoning:
--   - Goblin: short, hunched, big-eared, holding a crude blade.
--   - Zombie: human-height, slouched, one arm slack, one reaching.
--   - Trader: a plain unarmed robed silhouette with a satchel.
--   - Guard: an armored humanoid with a spear and round shield.
--   - High Guard: taller/bulkier than Guard, pauldrons, a plumed helm,
--     gold trim, a longsword — the same family, visibly the officer.
--   - Daemon: upright and disciplined, dark-iron armor plating, small
--     backswept horns, a long tail.
--   - Demon: squat and wide, a low crouching stance, oversized clawed
--     arms — the deliberate opposite silhouette from Daemon.
--   - Witch: a tall robed silhouette with a pointed hat and a staff.
-- `on conflict (id) do nothing` keeps this idempotent the same way every
-- other seeded-preset migration in this codebase is (0016/0053/0055/0059/
-- 0066 precedent), including the same "another agent may already have
-- applied an equivalent seed" tolerance.
insert into public.asset_library (id, name, source_type, model_ref) values
  ('a55e7022-0000-4000-8000-000000000022', 'Goblin', 'preset', '/assets/presets/goblin.glb'),
  ('a55e7023-0000-4000-8000-000000000023', 'Zombie', 'preset', '/assets/presets/zombie.glb'),
  ('a55e7024-0000-4000-8000-000000000024', 'Trader', 'preset', '/assets/presets/trader.glb'),
  ('a55e7025-0000-4000-8000-000000000025', 'Guard', 'preset', '/assets/presets/guard.glb'),
  ('a55e7026-0000-4000-8000-000000000026', 'High Guard', 'preset', '/assets/presets/high-guard.glb'),
  ('a55e7027-0000-4000-8000-000000000027', 'Daemon', 'preset', '/assets/presets/daemon.glb'),
  ('a55e7028-0000-4000-8000-000000000028', 'Demon', 'preset', '/assets/presets/demon.glb'),
  ('a55e7029-0000-4000-8000-000000000029', 'Witch', 'preset', '/assets/presets/witch.glb')
on conflict (id) do nothing;

-- Link each of 0073's 8 seeded templates to its own new preset above, by
-- name (monster_templates.name is unique per 0073's schema) — a plain
-- `update ... where name in (...)`, not an on-conflict insert, so re-running
-- this migration is naturally idempotent (it just re-sets the same value)
-- without needing a guard condition.
update public.monster_templates set default_asset_id = case name
  when 'Goblin' then 'a55e7022-0000-4000-8000-000000000022'::uuid
  when 'Zombie' then 'a55e7023-0000-4000-8000-000000000023'::uuid
  when 'Trader' then 'a55e7024-0000-4000-8000-000000000024'::uuid
  when 'Guard' then 'a55e7025-0000-4000-8000-000000000025'::uuid
  when 'High Guard' then 'a55e7026-0000-4000-8000-000000000026'::uuid
  when 'Daemon' then 'a55e7027-0000-4000-8000-000000000027'::uuid
  when 'Demon' then 'a55e7028-0000-4000-8000-000000000028'::uuid
  when 'Witch' then 'a55e7029-0000-4000-8000-000000000029'::uuid
  else default_asset_id
end
where name in ('Goblin', 'Zombie', 'Trader', 'Guard', 'High Guard', 'Daemon', 'Demon', 'Witch');
