-- Tavern furniture/decoration presets (project owner's own request: "a
-- batch of new decorative/furniture presets ... for building tavern
-- scenes") — no schema changes needed (asset_library already has everything
-- a preset row needs), just 5 new built-in preset rows for the props
-- generated by scripts/assets/generate-tavern-presets.mjs:
--   - "Bar Counter" (bar-counter.glb): a straight tavern bar segment — a
--     dark-wood cabinet, a lighter overhanging bar top, a footrail, and 3
--     small decorative beer taps built directly into the countertop.
--   - "Bar Corner" (bar-corner.glb): a GENUINELY CURVED quarter-annulus
--     corner segment (not a mitered 45° fallback — the curved geometry
--     rendered cleanly on this task's own real screenshot, so no fallback
--     was needed; see generate-tavern-presets.mjs's own comment on
--     annularSectorSlab for exactly why this was judged worth shipping).
--   - "Beer Pump" (beer-pump.glb): a standalone traditional hand-pump
--     ("beer engine") fixture, distinct from Bar Counter's own simpler
--     built-in taps.
--   - "Glass" (glass.glb): a small pewter tankard — an ordinary small
--     placeable prop, not tied to any surface-detection logic (a DM places
--     it manually, like every other small decorative prop).
--   - "Food Plate" (food-plate.glb): a shallow ceramic plate with a bread
--     roll and garnish, same "ordinary small prop" treatment as Glass.
--
-- Every preset here is auto-normalized to fit a SINGLE cell at render time
-- (PlacedObject.tsx's existing maxDim-based scaling, unchanged) — the same
-- "model-village scale" convention every other built-in preset (Chest,
-- Tree, Table, the Batch A8a buildings, ...) already uses. Bar Counter and
-- Bar Corner do NOT use the wall-family's edge-to-edge WALL_FIT_TARGET_BY_URL
-- fit target: unlike wall segments, these don't need to visually butt up
-- against a neighboring copy of themselves, so this task found no strong
-- reason to deviate from the single-cell convention with a new multi-cell
-- tileable-segment mechanic.
--
-- Seeded via migration as postgres, bypassing RLS, the identical
-- 0016_asset_library_presets.sql / 0066_building_presets.sql reasoning:
-- 0015's insert policy forbids preset rows (campaign_id null) through the
-- app path, so presets are seeded data by design. Fixed UUIDs continue the
-- SAME a55e7NNN sequence 0074 established, one past its last (Witch, …029)
-- — keeps every built-in preset's identity in one inspectable numbering
-- scheme across environments.
--
-- `on conflict do nothing` guards re-application the same way every prior
-- preset-seeding migration does, in case a dev stack already has these rows
-- from a direct, non-migration-tracked application under a different
-- filename (other concurrent agents may apply migrations directly to the
-- shared dev DB during testing).
insert into public.asset_library (id, name, source_type, model_ref) values
  ('a55e7030-0000-4000-8000-000000000030', 'Bar Counter', 'preset', '/assets/presets/bar-counter.glb'),
  ('a55e7031-0000-4000-8000-000000000031', 'Bar Corner', 'preset', '/assets/presets/bar-corner.glb'),
  ('a55e7032-0000-4000-8000-000000000032', 'Beer Pump', 'preset', '/assets/presets/beer-pump.glb'),
  ('a55e7033-0000-4000-8000-000000000033', 'Glass', 'preset', '/assets/presets/glass.glb'),
  ('a55e7034-0000-4000-8000-000000000034', 'Food Plate', 'preset', '/assets/presets/food-plate.glb')
on conflict (id) do nothing;
