-- Chair placeable map preset (project owner's own request: "we also need
-- chairs, these should be able to be sat on by players NPCs and enemies")
-- — no schema changes needed (asset_library already has everything a
-- preset row needs), just 1 new built-in preset row for the model
-- generated by scripts/assets/generate-chair-preset.mjs: a plain wooden
-- dining chair (four legs, a seat, three backrest slats).
--
-- No new movement/occupancy mechanic required — confirmed via
-- src/rules-engine/movement.ts's computeReachableCells before writing this
-- migration: it never consults map_objects at all (only other tokens'
-- positions and cell terrain), so a token has always been free to move
-- onto any placed object's cell. A Chair is therefore immediately
-- "sittable" by any player, NPC, or hostile token the moment it exists.
--
-- Seeded via migration as postgres, bypassing RLS, the identical
-- 0016_asset_library_presets.sql / 0083_tavern_presets.sql reasoning:
-- 0015's insert policy forbids preset rows (campaign_id null) through the
-- app path, so presets are seeded data by design. Fixed UUID continues the
-- SAME a55e7NNN sequence 0082 established, one past its last (Stairs
-- (Half), ...035) — keeps every built-in preset's identity in one
-- inspectable numbering scheme across environments.
--
-- `on conflict do nothing` guards re-application the same way every prior
-- preset-seeding migration does, in case a dev stack already has this row
-- from a direct, non-migration-tracked application under a different
-- filename (other concurrent agents may apply migrations directly to the
-- shared dev DB during testing).
insert into public.asset_library (id, name, source_type, model_ref) values
  ('a55e7036-0000-4000-8000-000000000036', 'Chair', 'preset', '/assets/presets/chair.glb')
on conflict (id) do nothing;
