-- Three new wall-family preset map assets (project owner's own request:
-- "a T-junction, a genuine right-angle corner, and a curved corner") — no
-- schema changes needed (asset_library already has everything a preset row
-- needs), just 3 new built-in preset rows for the props generated by
-- scripts/assets/generate-wall-corner-variants.mjs:
--   - "Wall T-Junction" (wall-t.glb): a full straight run through the cell
--     plus one perpendicular stub arm — generate-wall-variants-presets.mjs's
--     existing "corner" (really a rotationally-symmetric 4-way plus) with
--     one arm dropped.
--   - "Wall Corner (Right Angle)" (wall-corner-l.glb): a GENUINE right-angle
--     turn — exactly two adjacent half-arms meeting at a real 90° bend,
--     unlike the existing "Wall Corner" preset (wall-corner.glb), which is
--     actually a symmetric 4-way plus, not a right angle.
--   - "Wall Corner (Curved)" (wall-corner-curved.glb): a GENUINELY CURVED
--     quarter-annulus corner, built with the same annularSectorSlab
--     technique generate-tavern-presets.mjs's own Bar Corner uses, called
--     with wall-thickness/height-derived radii instead of the tavern bar's
--     own proportions.
--
-- The right-angle corner and the T-junction are both orientation-dependent
-- (which side(s) their arm(s) point toward) — the DM reaches all 4
-- rotations with the map editor's ordinary 90°-increment rotate control
-- (MapEditor.tsx's handleRotate already generalizes to any preset with no
-- code changes needed), the same way the existing wall-diagonal.glb's own
-- single canonical orientation already covers all 4 diagonal directions.
--
-- Seeded via migration as postgres, bypassing RLS, the identical
-- 0016_asset_library_presets.sql / 0055 (wall-corner/wall-diagonal/
-- wall-door) / 0083_tavern_presets.sql reasoning: 0015's insert policy
-- forbids preset rows (campaign_id null) through the app path, so presets
-- are seeded data by design. Fixed UUIDs continue the same a55e7NNN
-- sequence (a55e7035 was the last row seeded as of this migration), with a
-- deliberate gap (…040-…042, not …036-…038) to reduce collision risk
-- against other in-flight parallel migrations seeding their own new preset
-- rows concurrently.
--
-- `on conflict do nothing` guards re-application the same way every prior
-- preset-seeding migration does, in case a dev stack already has these rows
-- from a direct, non-migration-tracked application under a different
-- filename (other concurrent agents may apply migrations directly to the
-- shared dev DB during testing).
insert into public.asset_library (id, name, source_type, model_ref) values
  ('a55e7040-0000-4000-8000-000000000040', 'Wall T-Junction', 'preset', '/assets/presets/wall-t.glb'),
  ('a55e7041-0000-4000-8000-000000000041', 'Wall Corner (Right Angle)', 'preset', '/assets/presets/wall-corner-l.glb'),
  ('a55e7042-0000-4000-8000-000000000042', 'Wall Corner (Curved)', 'preset', '/assets/presets/wall-corner-curved.glb')
on conflict (id) do nothing;
