// Generated by scripts/assets/generate-avatar-presets.mjs — do not edit by hand.

export interface AvatarPreset {
  id: string;
  label: string;
  file: string;
}

export const AVATAR_PRESETS: readonly AvatarPreset[] = [
  { id: "vanguard", label: "Vanguard", file: "/avatars/presets/vanguard.glb" },
  { id: "mystic", label: "Mystic", file: "/avatars/presets/mystic.glb" },
  { id: "warden", label: "Warden", file: "/avatars/presets/warden.glb" },
  { id: "corsair", label: "Corsair", file: "/avatars/presets/corsair.glb" },
  { id: "ember", label: "Ember", file: "/avatars/presets/ember.glb" },
] as const;
